// Generated by npm run build. Cache scope: this game only.
self.GAME_OFFLINE={
  "prefix": "iron-citadel-",
  "version": "cf714b2e3990",
  "assets": [
    "./",
    "./art.js",
    "./cover.svg",
    "./cover.webp",
    "./engine.js",
    "./game.js",
    "./game.json",
    "./icon.svg",
    "./index.html",
    "./scene.js",
    "./styles.css",
    "../../studio/combat.js",
    "../../studio/core.js",
    "../../studio/models.js",
    "../../studio/passport.js",
    "../../studio/renderer.js",
    "../../studio/shaders.js",
    "../../studio/shell.js",
    "../../studio/studio.css",
    "../../studio/worker.js"
  ]
};
importScripts('../../studio/worker.js');
