import {Studio} from '../../studio/shell.js';
import {Batch,humanoid,house,tree,crate,burst,particles} from '../../studio/models.js';
import {clamp,seeded,starsFor} from '../../studio/core.js';
const names=['Home street','Market shortcuts','Sweet escape','School run','Garden lanes','The long jump','Monsoon market','Rooftop road','Festival dash','Old town','The great chase','Home before sunset'];
export const config={slug:'chikoo-bunty',name:'Chikoo & Bunty',title:'MISCHIEF<br><em>CHASE.</em>',genre:'3D RUNNER',accent:'#f3cf8c',tagline:'A whole neighborhood of trouble. Jump, slide, and find your own way home.',subtitle:'CATCH US IF YOU CAN.',levels:names.map((name,i)=>({name,goal:`Reach the finish. Collect ${12+i*3} laddoos for a bonus star.${i>0?' Jump low barriers; slide under banners.':''}`})),options:[{key:'brother',label:'CHOOSE YOUR BROTHER',values:[['chikoo','Chikoo · 4 hearts'],['bunty','Bunty · higher jump']]}],buttons:[{id:'primary',label:'JUMP',icon:'↑'},{id:'special',label:'DASH',icon:'ϟ'},{id:'aux',label:'SLIDE',icon:'↓'}],help:'Swipe left or right, or move the stick sideways, to change lanes. JUMP over low barriers and SLIDE beneath banners. Change lanes around market carts. DASH protects you and attracts nearby laddoos for a few seconds. Chikoo gets an extra heart; Bunty jumps higher. Reach the finish to unlock the next neighborhood.',keys:'Left / right change lanes · Space / J jump · E / down slide · K dash · swipe works anywhere on the scene',graphics:{fog:[.79,.74,.62],sun:[-.65,.8,.4],lightColor:[1,.89,.71],exposure:1.2,fogNear:35,fogFar:98,shadowRadius:26}};
export class Chase{
 constructor(s){this.s=s;}
 start(level,diff,options){this.level=level;this.diff=diff;this.brother=options.brother||'chikoo';this.maxHp=this.brother==='chikoo'?4:3;this.hp=this.maxHp;this.distance=0;this.goal=420+level*55;this.speed=(11.7+level*.48)*diff.speed;this.lane=1;this.x=0;this.y=0;this.vy=0;this.slide=0;this.dash=0;this.dashCd=0;this.invulnerable=0;this.moveCd=0;this.coins=0;this.score=0;this.obstacles=[];this.pickups=[];this.fx=[];this.random=seeded(187+level);this.chunk=-1;this.prepareTrack();this.rebuild();this.resize();this.hud();}
 prepareTrack(){for(let d=32;d<this.goal-14;d+=Math.max(10,18-this.level*.5)){const safe=Math.floor(this.random()*3),blocked=[0,1,2].filter(v=>v!==safe);if(this.level<2)blocked.splice(1,1);for(const lane of blocked){const type=this.level===0?'hurdle':['hurdle','banner','cart'][Math.floor(this.random()*3)];this.obstacles.push({d,lane,type,hit:false});}for(let j=0;j<3;j++)this.pickups.push({d:d-5+j*2,lane:safe,collected:false});}}
 rebuild(){const b=new Batch(),chunk=Math.floor(this.distance/55),start=chunk*55-20,end=start+165,rng=seeded(800+Math.floor(start/10));this.chunk=chunk;b.add('box',[0,-.2,-(start+end)/2],[7,.2,(end-start)/2],'#a99e85');for(const x of [-5.2,5.2])b.add('box',[x,.08,-(start+end)/2],[.75,.09,(end-start)/2],'#c2b294');for(let d=Math.floor(start/5)*5;d<end;d+=5){for(const x of [-1.35,1.35])b.add('box',[x,.012,-d],[.025,.015,.9],'#d4c2a0');for(const side of [-1,1]){const x=side*(8+rng()*1.6),colors=['#d1b394','#c1ada1','#b9c2af','#9baeb0'];if(d%10===0){house(b,x,-d,{w:2.1,h:4+rng()*5,d:2.5,color:colors[Math.floor(rng()*4)]});b.add('box',[x-side*.5,2.5,-d+2.7],[2,.1,.8],['#b77d62','#ae9d64','#709c91'][Math.floor(rng()*3)]);tree(b,x+side*3,-d,1.4,'#6d8260');}}}if(this.goal>=start&&this.goal<end){for(const x of [-4.5,4.5])b.add('cylinder',[x,2,-this.goal],[.08,2,.08],'#627477');b.add('box',[0,3.5,-this.goal],[4.6,.35,.07],'#d2bb78');for(let i=-4;i<=4;i++)b.add('box',[i,3.5,-this.goal+.09],[.25,.32,.04],i%2?'#344d4f':'#f0e3ba');}this.s.setWorld(b);}
 resize(){this.s.renderer.fov=this.s.renderer.aspect<.85?.96:.72;}
 changeLane(delta){this.lane=clamp(this.lane+delta,0,2);this.moveCd=.21;}
 key(code){if(code==='ArrowLeft'||code==='KeyA')this.changeLane(-1);if(code==='ArrowRight'||code==='KeyD')this.changeLane(1);if(code==='ArrowUp'||code==='KeyW')this.action('primary');if(code==='ArrowDown'||code==='KeyS')this.action('aux');}
 swipe(dx,dy){if(Math.abs(dx)>Math.abs(dy))this.changeLane(Math.sign(dx));else this.action(dy<0?'primary':'aux');}
 action(id){if(id==='primary'&&this.y<=.02){this.vy=this.brother==='bunty'?9.5:8.3;this.slide=0;this.s.tone(440,.08);}if(id==='aux'&&this.y<=.05)this.slide=.95;if(id==='special'&&this.dashCd<=0){this.dash=4.5;this.dashCd=16;this.s.tone(640,.16);this.s.toast('Dash! Protected and attracting laddoos.');}}
 update(dt,input){this.moveCd=Math.max(0,this.moveCd-dt);if(this.moveCd<=0&&Math.abs(this.s.stick.x)>.5)this.changeLane(Math.sign(this.s.stick.x));this.x+=(this.lane*2.7-2.7-this.x)*Math.min(1,dt*14);this.slide=Math.max(0,this.slide-dt);this.dash=Math.max(0,this.dash-dt);this.dashCd=Math.max(0,this.dashCd-dt);this.invulnerable=Math.max(0,this.invulnerable-dt);this.vy-=20*dt;this.y=Math.max(0,this.y+this.vy*dt);if(this.y===0)this.vy=0;this.distance+=this.speed*dt*(this.dash>0?1.28:1);this.score=Math.floor(this.distance)+this.coins*25;if(Math.floor(this.distance/55)!==this.chunk)this.rebuild();
  for(const o of this.obstacles){if(o.hit||Math.abs(o.d-this.distance)>1.05||Math.abs(o.lane*2.7-2.7-this.x)>1)continue;const safe=this.dash>0||o.type==='hurdle'&&this.y>.80||o.type==='banner'&&this.slide>0;if(!safe&&this.invulnerable<=0){this.hp--;this.invulnerable=1.4;burst(this.fx,this.x,1,-this.distance,'#f5cf9a',18);this.s.tone(110,.2);this.s.toast(o.type==='banner'?'Slide under the banner!':o.type==='cart'?'Change lanes around market carts.':'Jump over low barriers!');}o.hit=true;}
  for(const v of this.pickups){if(!v.collected&&Math.abs(v.d-this.distance)<(this.dash>0?4:1.25)&&Math.abs(v.lane*2.7-2.7-this.x)<(this.dash>0?8:1)){v.collected=true;this.coins++;if(this.coins%3===0)this.s.tone(800,.04);burst(this.fx,this.x,1,-this.distance,'#f1d486',3);}}
  if(this.hp<=0){this.s.finish(false,{score:this.score,message:'Watch the next obstacle: jump low barriers, slide under banners, or switch to a clear lane.'});return;}if(this.distance>=this.goal){const bonus=this.coins>=12+this.level*3,health=this.hp/this.maxHp*100;this.s.finish(true,{score:this.score+this.hp*150,stars:bonus&&health>=75?3:bonus||health>=50?2:1,message:`Home safe! ${this.coins} laddoos collected and ${this.hp} hearts remaining.`});return;}this.s.renderer.target=[this.x*.3,1,-this.distance-13];this.s.renderer.eye=[this.x*.15,6.2,-this.distance+12];}
 draw(b,dt){const z=-this.distance;humanoid(b,[this.x,this.y,z],Math.PI,{type:this.brother,color:this.brother==='chikoo'?'#d6af52':'#b75e4e',trim:'#343e55',time:this.s.time*1.25,walk:!this.slide,scale:this.slide>.05?.58:.95});if(this.dash>0){b.add('cylinder',[this.x,.06,z],[.85,.025,.85],'#d6e5b0');if(Math.floor(this.s.time*20)%2===0)burst(this.fx,this.x,.5,z+1,'#b7e6d5',1);}for(const o of this.obstacles){const dz=o.d-this.distance;if(dz< -6||dz>70)continue;const x=o.lane*2.7-2.7,z=-o.d;if(o.type==='hurdle'){b.add('box',[x,.42,z],[1,.42,.35],'#a77353');b.add('box',[x,.87,z],[1.12,.05,.4],'#ead29b');}else if(o.type==='banner'){for(const side of [-1,1])b.add('cylinder',[x+side*1.1,1.7,z],[.055,1.7,.055],'#777361');b.add('box',[x,2.18,z],[1.16,.7,.1],'#b6865e');b.add('box',[x,2.5,z+.11],[.85,.07,.02],'#e4c999');}else{b.add('box',[x,.8,z],[1,.6,.75],'#75938b');b.add('box',[x,2,z],[1.2,.12,.95],'#b88362');for(const side of [-1,1]){b.add('cylinder',[x+side*.9,1.5,z],[.04,.6,.04],'#596f6d');b.add('sphere',[x+side*.8,.3,z],[.2,.25,.2],'#3f4a48');}}}for(const v of this.pickups)if(!v.collected&&v.d-this.distance> -3&&v.d-this.distance<65){b.add('sphere',[v.lane*2.7-2.7,.8+Math.sin(this.s.time*3+v.d)*.1,-v.d],[.22,.22,.22],'#e8b764');b.add('gem',[v.lane*2.7-2.7,.95,-v.d],[.09,.07,.09],'#f3d7a3');}particles(b,this.fx,dt);}
 hud(){this.s.hud(`${Math.max(0,Math.ceil(this.goal-this.distance))}m to home · ${this.coins}/${12+this.level*3} bonus laddoos`,this.distance/this.goal,[['HEARTS','♥'.repeat(Math.max(0,this.hp))],['LADDOOS',this.coins],['SCORE',this.score]]);this.s.button('special',this.dash>0?'DASHING':'DASH',this.dashCd);}
 snapshot(){return {distance:this.distance,hp:this.hp,lane:this.lane,x:this.x,y:this.y,slide:this.slide,dash:this.dash,coins:this.coins,score:this.score};}
}
if(typeof document!=='undefined')new Studio(config,Chase);
