import {Studio} from '../../studio/shell.js';
import {Batch,humanoid,robot,house,crate,rock,burst,particles} from '../../studio/models.js';
import {clamp,distance,seeded,starsFor,moveWithCover,segmentHitsBox} from '../../studio/core.js';
import {healthBar} from '../../studio/combat.js';
export const WEAPONS={rifle:{name:'Rifle',damage:24,rate:.15,mag:30,reload:1.3,range:17,pellets:1},pistol:{name:'Pistol',damage:44,rate:.34,mag:12,reload:.85,range:16,pellets:1},shotgun:{name:'Shotgun',damage:18,rate:.65,mag:8,reload:1.6,range:8,pellets:5},smg:{name:'SMG',damage:15,rate:.085,mag:36,reload:1.25,range:12,pellets:1}};
const names=['First contact','Cargo sweep','The sentinel','Crossfire yard','Supply route','Iron colossus','Night perimeter','Signal blackout','Twin sentinels','Last outpost','The gauntlet','Citadel protocol'];
export const config={slug:'world-strike',name:'World Strike',title:'WORLD<br><em>STRIKE.</em>',genre:'TACTICAL ACTION',accent:'#e5c68e',tagline:'Read the battlefield. Move between cover. Make every shot count.',subtitle:'ONE SQUAD. YOUR COMMAND.',levels:names.map((name,i)=>({name,goal:i%3===2?'Clear the assault waves and disable the armored sentinel.':i<2?'Clear each wave. Use cover and reload before advancing.':'Ranged bots flank your position. Dodge their warning beams.'})),options:[{key:'country',label:'YOUR FLAG',values:[['India','India'],['Japan','Japan'],['Brazil','Brazil'],['France','France'],['USA','USA'],['Australia','Australia']]},{key:'weapon',label:'LOADOUT',values:[['rifle','Rifle · balanced'],['pistol','Pistol · precise'],['shotgun','Shotgun · close range'],['smg','SMG · rapid fire']]}],buttons:[{id:'primary',label:'FIRE',icon:'⌖'},{id:'special',label:'EMP',icon:'ϟ'},{id:'aux',label:'RELOAD',icon:'↻'}],help:'Move with the left stick. Hold FIRE to target the nearest visible robot. Crates stop both sides’ shots. EMP disables nearby robots and clears enemy projectiles. Pick up green supplies to repair armor. During a reload, press RELOAD again when it reads TAP NOW for an instant reload and six stronger shots. Your country is a cosmetic flag; every player has the same abilities.',graphics:{fog:[.57,.58,.52],sun:[-.5,.85,.3],lightColor:[1,.87,.67],exposure:1.25}};
export class Strike{
 constructor(s){this.s=s;}
 start(level,diff,options){this.level=level;this.diff=diff;this.random=seeded(321+level);this.weapon=WEAPONS[options.weapon]||WEAPONS.rifle;this.flag=options.country||'India';this.player={x:0,z:7,hp:100,yaw:Math.PI};this.enemies=[];this.bullets=[];this.fx=[];this.pickups=[];this.score=0;this.kills=0;this.shots=0;this.ammo=this.weapon.mag;this.cool=0;this.reload=0;this.emp=0;this.perfectReloads=0;this.precisionShots=0;this.reloadChecked=false;this.wave=0;this.waveTimer=1;this.totalWaves=2+Math.floor(level/3);this.cover=[{x:-6,z:1,w:1.6,d:.8},{x:6,z:1,w:1.6,d:.8},{x:0,z:-4,w:2,d:.6},{x:-10,z:-7,w:1,d:1.8},{x:10,z:-7,w:1,d:1.8},{x:-5,z:9,w:1.2,d:.7},{x:5,z:9,w:1.2,d:.7}];this.buildWorld();this.hud();}
 buildWorld(){const b=new Batch();b.add('box',[0,-.25,0],[24,.25,19],['#8c8d79','#777c77','#6a756f','#737b70'][Math.floor(this.level/3)]);for(let x=-18;x<=18;x+=3){b.add('box',[x,.015,0],[.018,.015,14],'#a8a895');}for(let z=-15;z<=15;z+=3)b.add('box',[0,.012,z],[18,.01,.016],'#a8a895');for(const c of this.cover){b.add('box',[c.x,.65,c.z],[c.w,.65,c.d],'#797d70');b.add('box',[c.x,1.32,c.z],[c.w+.05,.04,c.d+.05],'#b4ad8c');for(let x=c.x-c.w+.3;x<c.x+c.w;x+=.6)b.add('box',[x,.7,c.z+c.d+.015],[.025,.55,.02],'#404d4d');}for(let i=0;i<12;i++){const x=i<6?-22:22,z=-16+(i%6)*6;house(b,x,z,{h:4+i%3*2,w:2.2,d:2.2,color:'#919381'});crate(b,x+(i<6?4:-4),z,1.2);}for(let i=0;i<18;i++)rock(b,-35+i*4,-24-this.random()*12,3+this.random()*6,'#858b80');b.add('box',[0,.025,8],[1.7,.02,1.7],'#747d70');this.s.setWorld(b);this.s.renderer.eye=[0,26,27];this.s.renderer.target=[0,0,2];}
 spawn(){this.wave++;const n=4+Math.floor(this.level/2)+this.wave;for(let i=0;i<n;i++){const boss=this.level%3===2&&this.wave===this.totalWaves&&i===0,type=boss?'boss':this.level>0&&i%3===1?'ranged':this.level>3&&i%4===2?'runner':'guard';const hp=(boss?250+this.level*18:55+this.level*6)*(type==='runner'?.65:1);this.enemies.push({x:-15+(i/(n-1||1))*30,z:-11.7,hp,max:hp,type,yaw:0,cd:1+this.random()*2,charge:0,stun:0,flash:0});}this.s.toast(this.wave===this.totalWaves&&this.level%3===2?'Sentinel detected. Keep moving.':`Wave ${this.wave} / ${this.totalWaves}`,2200);}
 action(id){if(id==='aux'&&this.reload>0&&!this.reloadChecked){
 this.reloadChecked=true;const progress=1-this.reload/this.weapon.reload;
 if(progress>=.38&&progress<=.7){this.reload=0;this.ammo=this.weapon.mag;this.precisionShots=6;this.perfectReloads++;this.s.toast('Perfect reload · six empowered shots');this.s.tone(720,.12);}
 else this.s.toast('Too soon or late. The magazine is still reloading.');
 }else if(id==='aux'&&this.ammo<this.weapon.mag&&this.reload===0){this.reload=this.weapon.reload;this.reloadChecked=false;this.s.tone(180,.1);}if(id==='special'&&this.emp<=0){this.emp=10;for(const e of this.enemies)if(distance(e,this.player)<6){e.hp-=70;e.stun=3;e.charge=0;burst(this.fx,e.x,1,e.z,'#a0ece5',16);}this.bullets=this.bullets.filter(b=>!b.enemy);burst(this.fx,this.player.x,1,this.player.z,'#a0ece5',28);this.s.tone(160,.25);}}
 shoot(){if(this.cool>0||this.reload>0)return;if(!this.ammo){this.action('aux');return;}const p=this.player,targets=this.enemies.filter(e=>e.hp>0&&distance(p,e)<this.weapon.range&&!this.cover.some(c=>segmentHitsBox(p,e,c))).sort((a,b)=>distance(p,a)-distance(p,b));const target=targets[0];if(!target)return;p.yaw=Math.atan2(target.x-p.x,target.z-p.z);this.cool=this.weapon.rate;this.ammo--;this.shots++;const empowered=this.precisionShots>0;if(empowered)this.precisionShots--;for(let i=0;i<this.weapon.pellets;i++){const a=p.yaw+(i-(this.weapon.pellets-1)/2)*.085;this.bullets.push({x:p.x,z:p.z,vx:Math.sin(a)*34,vz:Math.cos(a)*34,life:this.weapon.range/34,damage:this.weapon.damage*(empowered?1.25:1),enemy:false});}this.s.tone(180,.05,'sawtooth');}
 update(dt,input){const p=this.player;this.cool=Math.max(0,this.cool-dt);this.emp=Math.max(0,this.emp-dt);if(this.reload>0){this.reload-=dt;if(this.reload<=0){this.reload=0;this.ammo=this.weapon.mag;}}moveWithCover(p,input.x*5.8*dt,input.z*5.8*dt,this.cover);this.moving=Math.hypot(input.x,input.z)>.1;if(this.moving&&this.cool<=0)p.yaw=Math.atan2(input.x,input.z);if(input.held('primary'))this.shoot();
  if(!this.enemies.length){this.waveTimer-=dt;if(this.waveTimer<=0){if(this.wave>=this.totalWaves){this.s.finish(true,{score:this.score+Math.round(p.hp*10),health:p.hp,stars:starsFor(p.hp)});return;}this.spawn();this.waveTimer=2.2;}}
  for(const e of this.enemies){e.flash=Math.max(0,e.flash-dt);e.stun=Math.max(0,e.stun-dt);if(e.hp<=0||e.stun>0)continue;const d=distance(p,e),speed=(e.type==='runner'?3.8:e.type==='boss'?1.1:1.8)*this.diff.speed;e.yaw=Math.atan2(p.x-e.x,p.z-e.z);const blocked=this.cover.some(c=>segmentHitsBox(e,p,c));if(d>(e.type==='ranged'?7:1.45)||blocked){let dx=Math.sin(e.yaw)*speed*dt,dz=Math.cos(e.yaw)*speed*dt;const x=e.x,z=e.z;moveWithCover(e,dx,dz,this.cover,.4);if(Math.hypot(x-e.x,z-e.z)<dt*.3){const side=e.x<0?-1:1;moveWithCover(e,side*speed*dt,0,this.cover,.4);}}
   if(e.type==='boss'&&e.hp<e.max*.5&&!e.phaseTwo){e.phaseTwo=true;e.cd=.8;this.s.toast('Sentinel overdrive · dodge the three-shot fan',3500);}e.cd-=dt;if(e.charge>0){e.charge-=dt;if(e.charge<=0){const a=Math.atan2(e.aim.z-e.z,e.aim.x-e.x);for(const offset of e.phaseTwo?[-.22,0,.22]:[0])this.bullets.push({x:e.x,z:e.z,vx:Math.cos(a+offset)*9,vz:Math.sin(a+offset)*9,life:2.5,damage:e.type==='boss'?20:12,enemy:true});e.cd=e.type==='boss'?(e.phaseTwo?.95:1.4):2.4;}}else if(e.cd<=0&&!blocked&&d<12&&(e.type==='ranged'||e.type==='boss')){e.charge=.7;e.aim={x:p.x,z:p.z};}else if(d<1.45&&e.cd<=0){p.hp-=12*this.diff.damage;e.cd=.85;burst(this.fx,p.x,1,p.z,'#ecad82',6);this.s.tone(85,.12);}}
  for(const b of this.bullets){const old={x:b.x,z:b.z};b.x+=b.vx*dt;b.z+=b.vz*dt;b.life-=dt;if(this.cover.some(c=>segmentHitsBox(old,b,c))){b.life=0;burst(this.fx,b.x,1,b.z,'#d6c69e',3);continue;}if(b.enemy){if(distance(b,p)<.6){p.hp-=b.damage*this.diff.damage;b.life=0;this.s.tone(100,.12);}}else for(const e of this.enemies)if(e.hp>0&&distance(b,e)<(e.type==='boss'?.85:.55)){e.hp-=b.damage;e.flash=.1;b.life=0;burst(this.fx,e.x,1,e.z,'#e8c999',4);break;}}
  this.bullets=this.bullets.filter(b=>b.life>0);this.enemies=this.enemies.filter(e=>{if(e.hp>0)return true;this.kills++;this.score+=e.type==='boss'?800:100;burst(this.fx,e.x,1,e.z,'#9ee4df',12);if(this.kills%4===0)this.pickups.push({x:e.x,z:e.z});return false;});this.pickups=this.pickups.filter(v=>{if(distance(v,p)<1.2){p.hp=Math.min(100,p.hp+22);this.ammo=this.weapon.mag;this.s.toast('Armor repaired +22 · magazine refilled');return false;}return true;});if(p.hp<=0){this.s.finish(false,{score:this.score,health:0});return;}
  const target=[clamp(p.x,-8,8),0,clamp(p.z,-5,5)],portrait=this.s.renderer.aspect<.8,zoom=portrait?1.15:1;this.s.renderer.target=target;this.s.renderer.eye=[target[0],24*zoom,target[2]+21*zoom];}
 draw(b,dt){const p=this.player;humanoid(b,[p.x,0,p.z],p.yaw,{type:'soldier',color:'#526d68',time:this.s.time,walk:this.moving,attack:this.cool>0?.6:0});for(const e of this.enemies){healthBar(b,e);robot(b,[e.x,0,e.z],e.yaw,{color:e.type==='boss'?'#697c79':e.type==='ranged'?'#a88564':'#78766b',scale:e.type==='boss'?1.65:1,flash:e.flash>0,time:this.s.time});if(e.charge>0)b.segment([e.x,1,e.z],[e.aim.x,.07,e.aim.z],.017,'#ee997b');if(e.stun>0)b.add('gem',[e.x,2.3,e.z],[.12,.24,.12],'#a0eee4');}for(const v of this.pickups){b.add('box',[v.x,.28,v.z],[.3,.28,.3],'#639b78');b.add('box',[v.x,.57,v.z],[.18,.015,.06],'#ddf3d6');b.add('box',[v.x,.575,v.z],[.06,.015,.18],'#ddf3d6');}for(const v of this.bullets)b.segment([v.x,1,v.z],[v.x-v.vx*.025,1,v.z-v.vz*.025],.04,v.enemy?'#fa9871':'#fff1bf');particles(b,this.fx,dt);}
 hud(){this.s.hud(`Clear the outpost · Wave ${Math.max(1,this.wave)} / ${this.totalWaves}`,(this.wave-1+(this.enemies.length?0:.9))/this.totalWaves,[['ARMOR',Math.max(0,Math.ceil(this.player.hp))],['AMMO',this.reload>0?'…':this.ammo],['BOTS',this.enemies.length],['FLAG',this.flag]]);this.s.button('special','EMP',this.emp);const progress=1-this.reload/this.weapon.reload,window=this.reload>0&&!this.reloadChecked&&progress>=.38&&progress<=.7;this.s.button('aux',window?'TAP NOW':this.reload>0?'LOADING':'RELOAD',window?0:this.reload);}
 goals(){return [{label:'Perfect reloads',value:this.perfectReloads,target:2},{label:'Clear waves',value:this.wave-(this.enemies.length?1:0),target:this.totalWaves}];}
 bossInfo(){const e=this.enemies.find(e=>e.type==='boss'&&e.hp>0);return e?{name:'Armored sentinel',hp:e.hp,max:e.max,phase:e.phaseTwo?2:1}:null;}
 snapshot(){return {hp:this.player.hp,player:{...this.player},enemies:this.enemies.length,wave:this.wave,ammo:this.ammo,reload:this.reload,emp:this.emp,perfectReloads:this.perfectReloads,score:this.score};}
}
if(typeof document!=='undefined')new Studio(config,Strike);
