export const DIFFICULTIES={story:{name:'Explorer',damage:.6,speed:.82,reward:1},normal:{name:'Adventurer',damage:1,speed:1,reward:1.3},expert:{name:'Legend',damage:1.4,speed:1.16,reward:1.7}};
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function seeded(seed=1){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function readProgress(slug,count=12){let p;try{p=JSON.parse(localStorage.getItem('tz-studio-'+slug)||'null');}catch{}return normalizeProgress(p,count);}
export function normalizeProgress(p,count=12){return {version:1,unlocked:clamp(Math.floor(Number(p?.unlocked)||0),0,count-1),stars:Array.from({length:count},(_,i)=>clamp(Math.floor(Number(p?.stars?.[i])||0),0,3)),best:Math.max(0,Number(p?.best)||0),last:clamp(Math.floor(Number(p?.last)||0),0,count-1),difficulty:DIFFICULTIES[p?.difficulty]?p.difficulty:'story',muted:p?.muted!==false,options:p?.options&&typeof p.options==='object'?p.options:{}};}
export function completeLevel(progress,level,stars,score,count=12){if(!Number.isInteger(level)||level<0||level>=count)return progress;progress.stars[level]=Math.max(progress.stars[level]||0,clamp(Math.floor(stars),1,3));progress.best=Math.max(progress.best,Math.max(0,Math.floor(score)||0));progress.unlocked=Math.max(progress.unlocked,Math.min(count-1,level+1));progress.last=Math.min(count-1,level+1);return progress;}
export function saveProgress(slug,p){try{localStorage.setItem('tz-studio-'+slug,JSON.stringify(p));return true;}catch{return false;}}
export function pathInfo(points){let total=0;const segments=[];for(let i=1;i<points.length;i++){const [x,z]=points[i-1],[nx,nz]=points[i],length=Math.hypot(nx-x,nz-z);segments.push({x,z,dx:(nx-x)/length,dz:(nz-z)/length,start:total,length});total+=length;}return {segments,total};}
export function pointOnPath(path,d){const s=path.segments.find(s=>d<=s.start+s.length)||path.segments.at(-1),v=clamp(d-s.start,0,s.length);return {x:s.x+s.dx*v,z:s.z+s.dz*v,yaw:Math.atan2(s.dx,s.dz)};}
export function starsFor(health,bonus=true){return health>=75&&bonus?3:health>=40?2:1;}
export function moveWithCover(p,dx,dz,cover,r=.45){const fits=(x,z)=>Math.abs(x)<17-r&&Math.abs(z)<13-r&&!cover.some(c=>Math.abs(x-c.x)<c.w+r&&Math.abs(z-c.z)<c.d+r);if(fits(p.x+dx,p.z))p.x+=dx;if(fits(p.x,p.z+dz))p.z+=dz;}
export function segmentHitsBox(a,b,c,pad=0){let lo=0,hi=1;for(const [axis,half]of [['x','w'],['z','d']]){const d=b[axis]-a[axis],min=c[axis]-c[half]-pad,max=c[axis]+c[half]+pad;if(Math.abs(d)<1e-9){if(a[axis]<min||a[axis]>max)return false;continue;}let u=(min-a[axis])/d,v=(max-a[axis])/d;if(u>v)[u,v]=[v,u];lo=Math.max(lo,u);hi=Math.min(hi,v);if(lo>hi)return false;}return true;}
