import { Renderer, Batch } from './renderer.js';
import { DIFFICULTIES, readProgress, saveProgress, completeLevel, clamp } from './core.js';
const $=id=>document.getElementById(id);
export class Studio {
  constructor(config,Game){
    this.config=config;this.Game=Game;this.progress=readProgress(config.slug,config.levels.length);this.level=Math.min(this.progress.last,this.progress.unlocked);this.mode='menu';this.keys=new Set();this.actions=new Set();this.stick={x:0,z:0,id:null};this.batch=new Batch();this.last=0;this.time=0;this.frameCount=0;this.fps=0;this.fpsClock=0;this.uiClock=0;
    document.title=config.name+' · Tishaan’s Game Zone';document.body.style.setProperty('--accent',config.accent||'#bbdbab');
    document.body.innerHTML=`<header class="studio-top"><a href="../../" aria-label="Back to Tishaan’s Game Zone"><span class="zone-glyph">T</span> GAME ZONE</a><div class="studio-wordmark">${config.name}</div><div class="top-buttons"><button id="sound" aria-label="Turn sound on">♪</button><button id="pause" aria-label="Pause game" hidden>Ⅱ</button></div></header>
    <main><section id="menu" class="studio-menu"><div class="menu-art" style="background-image:url('./cover.webp')"></div><div class="menu-content"><div class="eyebrow">TISHAAN’S GAME ZONE <span>•</span> ${config.genre}</div><h1>${config.title||config.name}</h1><p class="tagline">${config.tagline}</p><div class="facts"><span>${config.levels.length} MISSIONS</span><span>3 DIFFICULTIES</span><span>LOCAL SAVE</span></div><div class="launch-card"><div class="launch-top"><div><small id="region"></small><h2 id="mission-name"></h2></div><button id="mission-toggle" class="text-button">Mission select ↗</button></div><p id="mission-goal"></p><div id="mission-grid" class="mission-grid" hidden></div><div class="setup-options"><label>DIFFICULTY<select id="difficulty">${Object.entries(DIFFICULTIES).map(([id,d])=>`<option value="${id}">${d.name}${id==='story'?' · gentle':id==='expert'?' · hard':' · balanced'}</option>`).join('')}</select></label>${(config.options||[]).map(o=>`<label>${o.label}<select id="option-${o.key}">${o.values.map(v=>`<option value="${v[0]}">${v[1]}</option>`).join('')}</select></label>`).join('')}<label>GRAPHICS<select id="quality"><option value="balanced">Cinematic</option><option value="eco">Battery saver</option></select></label></div><button id="launch" class="primary">Play mission <span>↗</span></button><div class="save-line"><span id="save-status">Progress saves on this device</span><span id="star-total"></span></div></div><details class="briefing"><summary>How to play <span>＋</span></summary><p>${config.help}</p><p class="key-help">${config.keys||'WASD / arrows to move · J / Space to act · K for ability · E for skill · Escape to pause'}</p></details></div><div class="art-caption"><span>THE NEXT ADVENTURE</span><b>${config.subtitle||'BEGINS WITH YOU.'}</b></div></section>
    <section id="play" class="studio-play" hidden><canvas id="scene" aria-label="${config.name} game world" tabindex="0"></canvas><div class="scene-vignette"></div><div class="mission-hud"><div><small id="hud-level"></small><strong id="hud-objective"></strong><div class="objective-track"><i id="objective-fill"></i></div></div><div class="hud-stats" id="hud-stats"></div></div><div id="context-tools" class="context-tools"></div><div class="touch-controls"><div id="joystick" class="joystick" aria-label="Movement joystick"><i id="stick"></i><small>MOVE</small></div><div id="action-buttons" class="action-buttons">${config.buttons.map((b,i)=>`<button data-action="${b.id}" class="action ${i===0?'main-action':''}" aria-label="${b.label}"><b>${b.icon==='⌖'?'+':b.icon||['✦','◇','↻'][i]}</b><span>${b.label}</span><small id="cooldown-${b.id}"></small></button>`).join('')}</div></div><div id="toast" class="toast" role="status" aria-live="polite"></div><div id="dialog" class="studio-overlay" hidden><div class="dialog-card" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><small id="dialog-kicker"></small><h2 id="dialog-title"></h2><p id="dialog-copy"></p><div id="dialog-stars" class="result-stars"></div><div id="dialog-stats" class="result-stats"></div><button id="continue" class="primary"></button><button id="retry" class="secondary" hidden>Retry this mission</button><button id="return-menu" class="text-button">Mission select</button></div></div></section></main>`;
    $('difficulty').value=this.progress.difficulty;for(const o of config.options||[]){const el=$('option-'+o.key);if(o.values.some(v=>v[0]===this.progress.options[o.key]))el.value=this.progress.options[o.key];}
    $('launch').onclick=()=>this.start();$('mission-toggle').onclick=()=>{$('mission-grid').hidden=!$('mission-grid').hidden;};$('difficulty').onchange=()=>{this.progress.difficulty=$('difficulty').value;this.save();};$('sound').onclick=()=>{this.progress.muted=!this.progress.muted;this.syncSound();this.save();this.tone(440);};$('pause').onclick=()=>this.pause();$('continue').onclick=()=>this.mode==='paused'?this.resume():this.start();$('retry').onclick=()=>{this.level=this.completedLevel;this.start();};$('return-menu').onclick=()=>this.menu();
    this.setupInput();this.syncSound();this.updateMenu();document.body.dataset.mode='menu';
    if(['localhost','127.0.0.1'].includes(location.hostname))window.__STUDIO_TEST__={studio:this,snapshot:()=>({mode:this.mode,level:this.level,fps:this.fps,state:this.game?.snapshot?.(),progress:structuredClone(this.progress)}),win:()=>this.finish(true,{health:100,score:1000,stars:3}),lose:()=>this.finish(false,{health:0,score:0}),action:id=>this.game?.action?.(id),step:(dt)=>{if(this.mode==='playing')this.game.update(dt,this.input());}};
    if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).catch(()=>{});
  }
  syncSound(){$('sound').textContent=this.progress.muted?'♪':'♫';$('sound').setAttribute('aria-label',this.progress.muted?'Turn sound on':'Mute sound');$('sound').setAttribute('aria-pressed',String(!this.progress.muted));}
  save(){if(!saveProgress(this.config.slug,this.progress))$('save-status').textContent='Storage unavailable — progress lasts for this visit';}
  updateMenu(){const l=this.config.levels[this.level];$('region').textContent=`CHAPTER ${Math.floor(this.level/3)+1} / MISSION ${String(this.level+1).padStart(2,'0')}`;$('mission-name').textContent=l.name;$('mission-goal').textContent=l.goal;$('star-total').textContent=`${this.progress.stars.reduce((a,b)=>a+b,0)} / ${this.config.levels.length*3} ★`;$('mission-grid').innerHTML=this.config.levels.map((v,i)=>`<button data-level="${i}" ${i>this.progress.unlocked?'disabled':''} class="${i===this.level?'selected':''}" aria-label="Mission ${i+1}: ${v.name}${i>this.progress.unlocked?', locked':''}"><b>${String(i+1).padStart(2,'0')}</b><small>${this.progress.stars[i]?'★'.repeat(this.progress.stars[i]):i>this.progress.unlocked?'LOCKED':'PLAY'}</small></button>`).join('');$('mission-grid').querySelectorAll('button').forEach(b=>b.onclick=()=>{this.level=Number(b.dataset.level);this.updateMenu();});}
  start(){
    this.clearInput();this.time=0;this.progress.difficulty=$('difficulty').value;for(const o of this.config.options||[])this.progress.options[o.key]=$('option-'+o.key).value;this.progress.last=this.level;this.save();
    $('menu').hidden=true;$('play').hidden=false;$('pause').hidden=false;$('dialog').hidden=true;document.body.dataset.mode='playing';this.mode='playing';
    const eco=$('quality').value==='eco';try{if(!this.renderer)this.renderer=new Renderer($('scene'),{...this.config.graphics,pixelRatio:eco?1:1.5,shadows:!eco});this.renderer.options.shadows=!eco;this.renderer.options.pixelRatio=eco?1:1.5;this.renderer.resize();this.game=new this.Game(this);this.game.start(this.level,DIFFICULTIES[this.progress.difficulty],this.progress.options);this.last=performance.now();if(!this.frame)this.frame=requestAnimationFrame(t=>this.tick(t));this.tone(392,.18);this.toast(this.config.levels[this.level].goal,4500);$('scene').focus({preventScroll:true});}
    catch(e){console.error(e);this.mode='error';this.dialog('GRAPHICS INTERRUPTED','Let’s try again.',e.message||'The game could not start.','Reload game');$('continue').onclick=()=>location.reload();}
  }
  setWorld(batch){this.renderer.setStatic(batch);batch.data.length=0;}
  input(){let x=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0)+this.stick.x,z=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)+this.stick.z;const m=Math.max(1,Math.hypot(x,z));return{x:x/m,z:z/m,held:id=>this.actions.has(id),keys:this.keys};}
  tick(now){this.frame=null;const dt=Math.min(.035,Math.max(0,(now-this.last)/1000));this.last=now;if(this.mode==='playing'){
      this.time+=dt;this.game.update(dt,this.input());this.batch.reset();this.game.draw(this.batch,dt);this.renderer.render(this.batch);this.uiClock+=dt;if(this.uiClock>.1){this.uiClock=0;this.game.hud();}this.frameCount++;this.fpsClock+=dt;if(this.fpsClock>1){this.fps=this.frameCount/this.fpsClock;this.frameCount=0;this.fpsClock=0;}
    }if(this.mode!=='menu')this.frame=requestAnimationFrame(t=>this.tick(t));}
  hud(objective,progress,stats){$('hud-level').textContent=`MISSION ${String(this.level+1).padStart(2,'0')} · ${this.config.levels[this.level].name}`;$('hud-objective').textContent=objective;$('objective-fill').style.width=`${clamp(progress,0,1)*100}%`;$('hud-stats').innerHTML=stats.map(([label,value])=>`<div><small>${label}</small><b>${value}</b></div>`).join('');}
  button(id,label,cooldown=0){const b=document.querySelector(`[data-action="${id}"]`);if(!b)return;b.querySelector('span').textContent=label;b.querySelector('small').textContent=cooldown>0?Math.ceil(cooldown)+'s':'';b.classList.toggle('recharging',cooldown>0);}
  tools(html,handler){$('context-tools').innerHTML=html;$('context-tools').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(this.mode==='playing')handler(b.dataset.tool);});}
  toast(message,ms=2600){clearTimeout(this.toastTimer);$('toast').textContent=message;$('toast').classList.add('show');this.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),ms);}
  dialog(kicker,title,copy,button){$('dialog-kicker').textContent=kicker;$('dialog-title').textContent=title;$('dialog-copy').textContent=copy;$('continue').textContent=button;$('dialog').hidden=false;$('continue').focus({preventScroll:true});}
  pause(){if(this.mode!=='playing')return;this.mode='paused';this.clearInput();document.body.dataset.mode='paused';$('dialog-stars').textContent='';$('dialog-stats').innerHTML='';$('retry').hidden=true;this.dialog('TAKE A BREATHER','Adventure paused.','Your mission will resume from this moment.','Resume mission');}
  resume(){if(this.mode!=='paused')return;this.clearInput();this.mode='playing';document.body.dataset.mode='playing';$('dialog').hidden=true;this.last=performance.now();$('scene').focus({preventScroll:true});}
  menu(){this.mode='menu';this.clearInput();if(this.frame)cancelAnimationFrame(this.frame);this.frame=null;document.body.dataset.mode='menu';$('play').hidden=true;$('menu').hidden=false;$('pause').hidden=true;this.updateMenu();$('launch').focus();}
  finish(won,result={}){if(this.mode!=='playing')return;this.completedLevel=this.level;this.clearInput();this.mode='result';document.body.dataset.mode='result';const stars=won?result.stars||1:0;if(won){completeLevel(this.progress,this.level,stars,result.score,this.config.levels.length);this.level=Math.min(this.config.levels.length-1,this.level+1);}this.save();const last=this.completedLevel===this.config.levels.length-1;this.dialog(won?'MISSION COMPLETE':'ANOTHER CHANCE',won?last?'Campaign complete.':'Beautifully done.':'Your comeback starts here.',result.message||(won?'A new mission is ready. Replay any unlocked mission to improve your stars.':'Try a different strategy, or choose Explorer difficulty for a gentler challenge.'),won&&!last?'Next mission →':'Play again');if(won&&last)this.level=this.completedLevel;$('dialog-stars').textContent=won?'★'.repeat(stars)+'☆'.repeat(3-stars):'';$('dialog-stats').innerHTML=`<div><b>${Math.round(result.score||0)}</b><small>SCORE</small></div><div><b>${Math.round(this.time)}s</b><small>TIME</small></div><div><b>${this.progress.best}</b><small>BEST</small></div>`;$('retry').hidden=!won;this.tone(won?660:180,.3);}
  tone(freq=440,duration=.09,wave='triangle'){if(this.progress.muted)return;try{this.audio ||=new (window.AudioContext||window.webkitAudioContext)();this.audio.resume().catch(()=>{});const o=this.audio.createOscillator(),g=this.audio.createGain(),t=this.audio.currentTime;o.type=wave;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*.6,t+duration);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.audio.destination);o.start();o.stop(t+duration);o.onended=()=>{o.disconnect();g.disconnect();};}catch{}}
  clearInput(){this.keys.clear();this.actions.clear();this.stick.x=this.stick.z=0;this.stick.id=null;if($('stick'))$('stick').style.transform='';document.querySelectorAll('.action.pressed').forEach(b=>b.classList.remove('pressed'));}
  setupInput(){const joy=$('joystick'),move=e=>{const r=joy.getBoundingClientRect(),lim=r.width*.30,dx=e.clientX-r.x-r.width/2,dz=e.clientY-r.y-r.height/2,m=Math.max(lim,Math.hypot(dx,dz));this.stick.x=dx/m;this.stick.z=dz/m;$('stick').style.transform=`translate(${dx/m*lim}px,${dz/m*lim}px)`;};joy.onpointerdown=e=>{if(this.mode!=='playing')return;e.preventDefault();this.stick.id=e.pointerId;joy.setPointerCapture(e.pointerId);move(e);};joy.onpointermove=e=>{if(this.stick.id===e.pointerId)move(e);};const release=e=>{if(this.stick.id===e.pointerId){this.stick.x=this.stick.z=0;this.stick.id=null;$('stick').style.transform='';}};for(const event of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(event,release);
    document.querySelectorAll('[data-action]').forEach(b=>{b.onpointerdown=e=>{if(this.mode!=='playing')return;e.preventDefault();b.setPointerCapture(e.pointerId);this.actions.add(b.dataset.action);b.classList.add('pressed');this.game.action?.(b.dataset.action);};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{this.actions.delete(b.dataset.action);b.classList.remove('pressed');});});
    const mapping={Space:'primary',KeyJ:'primary',KeyK:'special',KeyE:'aux',KeyR:'aux',ShiftLeft:'special'};addEventListener('keydown',e=>{if(e.code==='Escape'){if(this.mode==='playing')this.pause();else if(this.mode==='paused')this.resume();return;}if(this.mode!=='playing'||e.target.matches('input,select,textarea'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(mapping[e.code]){this.actions.add(mapping[e.code]);if(!e.repeat)this.game.action?.(mapping[e.code]);}if(!e.repeat)this.game.key?.(e.code);});addEventListener('keyup',e=>{this.keys.delete(e.code);if(mapping[e.code])this.actions.delete(mapping[e.code]);});
    let down=null;$('scene').onpointerdown=e=>{down={x:e.clientX,y:e.clientY};};$('scene').onpointerup=e=>{if(this.mode!=='playing'||!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.hypot(dx,dy)>25)this.game.swipe?.(dx,dy);else this.game.tap?.(this.renderer.groundPoint(e.clientX,e.clientY));down=null;};$('scene').onpointercancel=()=>down=null;
    addEventListener('blur',()=>this.pause());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.pause();});addEventListener('resize',()=>{this.renderer?.resize();this.game?.resize?.();});$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();this.pause();this.toast('Graphics paused. Reload this mission to continue.',20000);});
  }
}
