import {Studio} from '../../studio/shell.js';
import {Batch,tower,tree,rock,house,robot,burst,particles} from '../../studio/models.js';
import {pathInfo,pointOnPath,distance,seeded,starsFor} from '../../studio/core.js';
export const TOWERS={arrow:{cost:75,range:5.6,damage:23,rate:.65},frost:{cost:100,range:5,damage:10,rate:1.05},cannon:{cost:140,range:6.5,damage:48,rate:1.7}};
const maps=[
 {path:[[-9,-11],[6,-11],[6,-4],[-6,-4],[-6,4],[5,4],[5,11]],pads:[[-6,-8],[-1,-8],[3,-8],[9,-6],[3,-1],[-2,-1],[-9,1],[-3,7],[1,7],[8,8],[-9,-7],[9,0]]},
 {path:[[-8,-12],[-8,-5],[5,-5],[5,2],[-6,2],[-6,9],[7,9],[7,12]],pads:[[-5,-9],[-4,-2],[1,-8],[8,-5],[8,0],[2,5],[-3,5],[-9,6],[-3,11],[3,12],[0,-1],[-10,-2]]},
 {path:[[-10,-11],[7,-11],[7,-2],[-7,-2],[-7,7],[5,7],[5,12]],pads:[[-6,-8],[-1,-8],[4,-7],[10,-5],[4,1],[-2,1],[-10,3],[-4,10],[1,10],[8,10],[1,-5],[-10,-5]]},
 {path:[[-9,-12],[-9,-5],[6,-5],[6,3],[-6,3],[-6,9],[7,9],[7,12]],pads:[[-6,-9],[-6,-2],[-1,-8],[3,-2],[9,-1],[3,6],[-2,6],[-9,7],[-3,12],[3,12],[0,0],[-11,1]]}
];
const names=['The first watch','Frost and fire','Stone guardian','River crossing','Armored march','The bridgebreaker','Winter pass','Frozen siege','Frost titan','Ember valley','Dragonfall','The final keep'];
export const config={slug:'dragon-keep',name:'Dragon Keep TD',title:'DRAGON<br><em>KEEP.</em>',genre:'TOWER STRATEGY',accent:'#cbd8ab',tagline:'Build a defense with purpose. Every tower has a role. Every path tells a story.',subtitle:'HOLD THE LAST LIGHT.',levels:names.map((name,i)=>({name,goal:i%3===2?'Build your defense and stop the guardian in the final wave.':i<2?'Tap a stone pad to build. Combine arrows, frost and cannon towers.':'Armored enemies resist arrows. Frost slows them; cannons break their armor.'})),buttons:[{id:'primary',label:'WAVE',icon:'▷'},{id:'special',label:'METEOR',icon:'☄'},{id:'aux',label:'UPGRADE',icon:'↑'}],help:'Choose a tower, then tap a round stone pad to build it. Tap an existing tower to select it. Arrow towers are fast, frost towers slow enemies, and cannons deal area damage that ignores armor. Upgrade or sell selected towers. Start waves when ready. Meteor hits the enemies nearest your selected pad. Every wave pays a bonus.',keys:'1 / 2 / 3 select a tower · click a pad to build · Space starts a wave · E upgrades · K calls a meteor',graphics:{fog:[.54,.66,.60],sun:[-.6,.9,.35],lightColor:[1,.93,.75],exposure:1.15,shadowRadius:38}};
export class Keep{
 constructor(s){this.s=s;}
 start(level,diff){this.level=level;this.diff=diff;this.map=maps[Math.floor(level/3)];this.path=pathInfo(this.map.path);this.pads=this.map.pads.map(([x,z])=>({x,z,tower:null}));this.selected=-1;this.type='arrow';this.gold=240+level*14;this.lives=20;this.score=0;this.wave=0;this.waves=3+Math.floor(level/3);this.queue=0;this.spawnTimer=0;this.enemies=[];this.shots=[];this.fx=[];this.meteor=0;this.runningWave=false;this.fast=false;this.random=seeded(level+90);this.buildWorld();this.tools();document.getElementById('joystick').style.visibility='hidden';this.hud();}
 buildWorld(){const b=new Batch(),winter=this.level>=6&&this.level<9;b.add('box',[0,-.3,0],[19,.3,20],winter?'#a4b5b2':'#6f8561');for(const seg of this.path.segments){const x=seg.x+seg.dx*seg.length/2,z=seg.z+seg.dz*seg.length/2;b.add('box',[x,.03,z],[seg.dx?seg.length/2+1:.96,.055,seg.dz?seg.length/2+1:.96],winter?'#869996':'#b0a68a');for(let d=0;d<seg.length;d+=.8){const p=pointOnPath(this.path,seg.start+d);b.add('box',[p.x,.094,p.z],[seg.dx?.018:.88,.014,seg.dz?.018:.88],winter?'#a6b4ae':'#928c76');}}
 for(const p of this.pads){b.add('cylinder',[p.x,.12,p.z],[.92,.13,.92],'#8d9680');b.add('cylinder',[p.x,.26,p.z],[.67,.025,.67],'#b7b89d');}for(let i=0;i<20;i++){const side=i%2?-1:1,x=side*(13+this.random()*6),z=-18+this.random()*36;tree(b,x,z,1+this.random()*.8,winter?'#718c87':'#426452');rock(b,x+1,z,1.1);}const end=this.map.path.at(-1);house(b,end[0],end[1]+2,{w:2,h:3,d:1.4,color:'#889085'});for(const x of [end[0]-2.2,end[0]+2.2]){b.add('cylinder',[x,1.8,end[1]+2],[.6,1.8,.6],'#8d968b');b.add('cone',[x,4,end[1]+2],[.9,.7,.9],'#596f6f');}this.s.setWorld(b);this.resize();}
 resize(){const r=this.s.renderer,portrait=r.aspect<.9;r.fov=portrait?1.08:.78;r.eye=portrait?[0,34,25]:[23,32,29];r.target=[0,0,0];}
 tools(){this.s.tools(Object.entries(TOWERS).map(([id,v])=>`<button data-tool="${id}" class="${this.type===id?'active':''}">${id.toUpperCase()} <b>${v.cost}g</b></button>`).join('')+`<button data-tool="sell" ${this.selected<0||!this.pads[this.selected].tower?'disabled':''}>SELL 65%</button><button data-tool="speed">${this.fast?'2× SPEED':'1× SPEED'}</button>`,id=>{if(TOWERS[id]){this.type=id;this.tools();}else if(id==='speed'){this.fast=!this.fast;this.tools();}else if(id==='sell'){const pad=this.pads[this.selected];if(pad?.tower){this.gold+=Math.floor(pad.tower.spent*.65);pad.tower=null;this.s.toast('Tower sold. Choose a new defense.');this.tools();}}});}
 key(code){if(['Digit1','Digit2','Digit3'].includes(code)){this.type=Object.keys(TOWERS)[Number(code.at(-1))-1];this.tools();}}
 tap(p){if(!p)return;const index=this.pads.findIndex(v=>Math.hypot(v.x-p[0],v.z-p[1])<1.45);if(index<0)return;this.selected=index;const pad=this.pads[index],spec=TOWERS[this.type];if(!pad.tower){if(this.gold<spec.cost){this.s.toast(`Need ${spec.cost} gold to build a ${this.type} tower.`);this.tools();return;}this.gold-=spec.cost;pad.tower={type:this.type,rank:1,cd:0,yaw:0,spent:spec.cost};this.s.tone(440);burst(this.fx,pad.x,1,pad.z,'#dae4b1',14);}else this.s.toast(`${pad.tower.type.toUpperCase()} rank ${pad.tower.rank} · upgrade ${this.upgradeCost(pad.tower)}g`);this.tools();this.hud();}
 upgradeCost(t){return Math.round(TOWERS[t.type].cost*.75*t.rank);}
 action(id){if(id==='primary'){if(this.runningWave){this.fast=!this.fast;this.tools();return;}if(this.wave<this.waves){if(!this.pads.some(p=>p.tower)){this.s.toast('Build at least one tower before calling the wave.');return;}this.wave++;this.queue=5+this.level+this.wave*2;this.spawnTimer=0;this.runningWave=true;this.s.toast(`Wave ${this.wave} · ${this.queue} enemies incoming`);}}else if(id==='aux'){const t=this.pads[this.selected]?.tower;if(!t){this.s.toast('Tap a tower to select it first.');return;}if(t.rank>=3){this.s.toast('This tower is fully upgraded.');return;}const cost=this.upgradeCost(t);if(this.gold<cost){this.s.toast(`Need ${cost} gold for this upgrade.`);return;}this.gold-=cost;t.spent+=cost;t.rank++;this.s.tone(620);this.s.toast(`Rank ${t.rank} · damage and range increased`);this.tools();}else if(id==='special'&&this.meteor<=0&&this.enemies.length){const focus=this.pads[this.selected]||this.enemies.reduce((a,b)=>a.progress>b.progress?a:b),target=this.enemies.slice().sort((a,b)=>distance(focus,a)-distance(focus,b))[0];for(const e of this.enemies)if(distance(e,target)<3.3){e.hp-=145;e.slow=2;}burst(this.fx,target.x,1,target.z,'#ffca82',35);this.meteor=18;this.s.tone(110,.3);}}
 update(dt){dt*=this.fast?2:1;this.meteor=Math.max(0,this.meteor-dt);if(this.runningWave&&this.queue>0){this.spawnTimer-=dt;if(this.spawnTimer<=0){this.spawnTimer=.82;const boss=this.level%3===2&&this.wave===this.waves&&this.queue===1,type=boss?'boss':this.level>2&&this.queue%4===0?'armor':this.queue%3===0?'fast':'normal',hp=(type==='boss'?440+this.level*35:type==='armor'?140:70)+this.level*7+this.wave*11;this.enemies.push({...pointOnPath(this.path,0),type,progress:0,hp,max:hp,speed:(type==='fast'?3.2:type==='boss'?1.3:2.1)*this.diff.speed,slow:0});this.queue--;}}
  for(const p of this.pads){const t=p.tower;if(!t)continue;t.cd-=dt;const spec=TOWERS[t.type],range=spec.range+(t.rank-1)*.8;const target=this.enemies.filter(e=>e.hp>0&&distance(p,e)<range).sort((a,b)=>b.progress-a.progress)[0];if(target){t.yaw=Math.atan2(target.x-p.x,target.z-p.z);if(t.cd<=0){t.cd=spec.rate/(1+(t.rank-1)*.12);this.shots.push({x:p.x,z:p.z,y:1.8,target,type:t.type,damage:spec.damage*(1+(t.rank-1)*.7),life:1.5});}}}
  for(const shot of this.shots){shot.life-=dt;const e=shot.target;if(e.hp<=0){shot.life=0;continue;}const d=distance(shot,e),speed=shot.type==='cannon'?18:25;if(d<speed*dt){const targets=shot.type==='cannon'?this.enemies.filter(v=>distance(v,e)<2):[e];for(const target of targets){const armor=target.type==='armor'&&shot.type!=='cannon'?.55:1;target.hp-=shot.damage*armor;if(shot.type==='frost')target.slow=2.4;}burst(this.fx,e.x,1,e.z,shot.type==='frost'?'#a8e8e5':'#e5c79b',4);shot.life=0;}else{shot.x+=(e.x-shot.x)/d*speed*dt;shot.z+=(e.z-shot.z)/d*speed*dt;shot.y+=(.8-shot.y)*dt*8;}}
  this.shots=this.shots.filter(s=>s.life>0);this.enemies=this.enemies.filter(e=>{if(e.hp<=0){this.gold+=e.type==='boss'?100:17;this.score+=e.type==='boss'?700:100;burst(this.fx,e.x,.8,e.z,'#d7e7b2',7);return false;}e.slow=Math.max(0,e.slow-dt);e.progress+=dt*e.speed*(e.slow>0?.45:1);Object.assign(e,pointOnPath(this.path,e.progress));if(e.progress>=this.path.total){this.lives-=e.type==='boss'?5:1;this.s.tone(110,.14);return false;}return true;});if(this.lives<=0){this.s.finish(false,{score:this.score,message:'The crystal needs a stronger defense. Use frost to hold enemies inside cannon range.'});return;}
  if(this.runningWave&&!this.queue&&!this.enemies.length){this.runningWave=false;this.gold+=65+this.wave*10;this.s.tone(620,.16);if(this.wave>=this.waves){this.s.finish(true,{score:this.score+this.lives*50,stars:starsFor(this.lives*5),message:`Crystal protected with ${this.lives}/20 integrity. Your tower strategy held the line.`});return;}this.s.toast('Wave cleared. Upgrade your towers, then call the next wave.',4000);}}
 draw(b,dt){for(let i=0;i<this.pads.length;i++){const p=this.pads[i];if(p.tower)tower(b,p.x,p.z,p.tower.type,p.tower.rank,p.tower.yaw);if(i===this.selected){const radius=p.tower?TOWERS[p.tower.type].range+(p.tower.rank-1)*.8:1.15;for(let j=0;j<32;j++){const a=j/32*Math.PI*2,c=(j+1)/32*Math.PI*2;b.segment([p.x+Math.cos(a)*radius,.11,p.z+Math.sin(a)*radius],[p.x+Math.cos(c)*radius,.11,p.z+Math.sin(c)*radius],.025,'#e4ebbf');}}}for(const e of this.enemies)robot(b,[e.x,.1,e.z],e.yaw,{color:e.type==='boss'?'#82795a':e.type==='armor'?'#738285':e.type==='fast'?'#95775c':'#84906c',scale:e.type==='boss'?1.4:.73,glow:e.slow>0?'#bffbff':'#efc286',time:this.s.time*2});for(const v of this.shots)b.add(v.type==='cannon'?'sphere':'gem',[v.x,v.y,v.z],v.type==='cannon'?[.14,.14,.14]:[.065,.14,.065],v.type==='frost'?'#b7f3f1':'#f4d899');const end=this.map.path.at(-1);b.add('gem',[end[0],3.9+Math.sin(this.s.time)*.12,end[1]+2],[.48,.9,.48],'#a5e6e2',[0,this.s.time*.3,0]);particles(b,this.fx,dt);}
 hud(){this.s.hud(this.runningWave?`Defend the crystal · Wave ${this.wave} / ${this.waves}`:'Build and upgrade · Call the next wave',(this.wave-(this.runningWave?1:0))/this.waves,[['CRYSTAL',`${this.lives}/20`],['GOLD',this.gold],['WAVE',`${this.wave}/${this.waves}`]]);this.s.button('primary',this.runningWave?(this.fast?'1× SPEED':'2× SPEED'):'WAVE');this.s.button('special','METEOR',this.meteor);const t=this.pads[this.selected]?.tower;this.s.button('aux',t&&t.rank<3?`${this.upgradeCost(t)}g ↑`:'UPGRADE');}
 snapshot(){return {lives:this.lives,gold:this.gold,wave:this.wave,queue:this.queue,enemies:this.enemies.length,towers:this.pads.filter(p=>p.tower).length,score:this.score};}
}
if(typeof document!=='undefined')new Studio(config,Keep);
