const CORE_KEY='monterra-wilds-save-v3';
const META_KEY='monterra-adventure-v1';
const FAMILY_NAMES=['Flame','Leaf','Tide','Spark','Stone'];
const FAMILY_COLOR=['#ed8b4b','#93c979','#75c6d7','#efcc64','#a2a7b7'];
const STRONG=[1,2,0,2,3];
const WEAK=[2,0,3,4,1];
const MISSION_DEFS=[
  {id:'first-trail',title:'First trail',detail:'Befriend 3 wild creatures.',field:'catches',goal:3,reward:35},
  {id:'battle-tested',title:'Battle tested',detail:'Win 5 encounters.',field:'wins',goal:5,reward:40},
  {id:'island-walker',title:'Island walker',detail:'Explore for 45 travel steps.',field:'steps',goal:45,reward:45},
  {id:'sigil-seeker',title:'Sigil seeker',detail:'Earn 2 guardian sigils.',field:'badges',goal:2,reward:55},
  {id:'wild-scholar',title:'Wild scholar',detail:'Befriend 8 wild creatures.',field:'catches',goal:8,reward:70},
  {id:'guardian-path',title:'Guardian path',detail:'Earn 4 guardian sigils.',field:'badges',goal:4,reward:90},
  {id:'island-champion',title:'Island champion',detail:'Earn all 6 guardian sigils.',field:'badges',goal:6,reward:150}
];
const ECOLOGY={
  'SUNPETAL MEADOW':{families:[1,3,0],text:'Spriglet herds graze near open flowers. Voltkit becomes bolder around dusk.'},
  'WHISPERWOOD':{families:[1,3,4],text:'Leaf creatures favour deep shade. Stone forms linger near old roots after rain.'},
  'CRYSTAL COAST':{families:[2,4,3],text:'Tide creatures dominate the shoreline. Mist draws rare stone forms closer to the water.'},
  'EMBER HIGHLANDS':{families:[0,4,3],text:'Flame creatures patrol warm ridges. Spark forms are most active in rough weather.'},
  'THE VERDANT ISLES':{families:[1,2,0],text:'The island is active. Travel farther from camp to discover specialised habitats.'}
};
const RIVALS=[
  {name:'Mara',title:'Coast tracker',line:'I have been following the same migration trail. Show me how your lead handles pressure.'},
  {name:'Kade',title:'Highland ranger',line:'Wild creatures react to confidence. Let us see whether yours trusts your decisions.'},
  {name:'Suri',title:'Field naturalist',line:'Battles reveal behaviour that observation alone cannot. One clean duel.'},
  {name:'Orin',title:'Sigil hunter',line:'You are making noise across Monterra. I want to know whether the stories are deserved.'}
];
function readCore(){try{return JSON.parse(localStorage.getItem(CORE_KEY)||'null')}catch{return null}}
function readMeta(){try{return Object.assign({renown:0,claimed:[],rivalWins:0,lastRivalAt:0,apexWon:false,title:'Trailborn'},JSON.parse(localStorage.getItem(META_KEY)||'{}'))}catch{return {renown:0,claimed:[],rivalWins:0,lastRivalAt:0,apexWon:false,title:'Trailborn'}}}
let meta=readMeta();
function writeMeta(){try{localStorage.setItem(META_KEY,JSON.stringify(meta))}catch{}}
function valueFor(state,field){return field==='badges'?(state.badges?.length||0):Math.max(0,Number(state[field])||0)}
function rank(){const r=meta.renown;return r>=600?'Apex Warden':r>=350?'Wilds Vanguard':r>=180?'Sigil Ranger':r>=80?'Trail Seeker':'Trailborn'}
function region(){return document.getElementById('region')?.textContent?.trim()||'THE VERDANT ISLES'}
function phase(){return document.getElementById('world-time')?.textContent?.trim()||'MORNING'}
function weather(){return document.getElementById('world-weather')?.textContent?.trim()||'CLEAR'}
function typeEffect(a,b){return STRONG[a]===b?1.45:WEAK[a]===b?.72:1}
function leadOf(state){const team=state?.team||[];return team[state?.active||0]||team[0]||{family:0,level:5,stage:0}}
function maxHp(m){return 44+(Number(m.level)||5)*7+(Number(m.stage)||0)*18}
function injectStyle(){const s=document.createElement('style');s.textContent=`
#adventure-btn{position:relative}.adventure-pulse{position:absolute;right:-3px;top:-3px;width:8px;height:8px;border-radius:50%;background:#f0c86f;box-shadow:0 0 0 4px rgba(240,200,111,.15)}
.ecology-chip{position:fixed;left:50%;bottom:max(17px,env(safe-area-inset-bottom));transform:translateX(-50%);z-index:12;max-width:min(560px,72vw);padding:7px 11px;border:1px solid rgba(255,255,255,.13);border-radius:999px;background:rgba(19,35,31,.48);backdrop-filter:blur(12px);color:#f4eedf;font:600 10px/1.25 system-ui,sans-serif;letter-spacing:.02em;text-align:center;pointer-events:none;transition:opacity .3s}
body:not([data-mode="explore"]) .ecology-chip{opacity:0}
.adventure-backdrop{position:fixed;inset:0;z-index:80;background:rgba(7,15,15,.72);backdrop-filter:blur(18px);display:grid;place-items:center;padding:18px}.adventure-backdrop[hidden]{display:none}.adventure-sheet{width:min(760px,100%);max-height:min(84vh,780px);overflow:auto;border:1px solid rgba(255,255,255,.14);border-radius:26px;background:linear-gradient(145deg,rgba(26,48,43,.98),rgba(18,32,30,.98));box-shadow:0 28px 80px rgba(0,0,0,.45);color:#f7f0de;padding:22px;font-family:system-ui,sans-serif}.adv-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.adv-head h2{font:700 clamp(28px,5vw,46px)/.95 Georgia,serif;margin:5px 0 8px}.adv-kicker{font:800 10px/1 system-ui;letter-spacing:.18em;color:#d4b96d}.adv-close{width:38px;height:38px;border-radius:50%;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.06);color:#fff;font-size:22px}.adv-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:18px 0}.adv-stat{padding:12px;border-radius:16px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.08)}.adv-stat small{display:block;font-size:9px;letter-spacing:.12em;color:#aebdb2}.adv-stat strong{font-size:17px}.adv-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.adv-card{padding:15px;border-radius:18px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.09)}.adv-card h3{margin:0 0 5px;font-size:15px}.adv-card p{margin:0;color:#bdc9c0;font-size:12px;line-height:1.45}.adv-mission{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid rgba(255,255,255,.07)}.adv-mission:first-of-type{border-top:0}.adv-progress{height:5px;margin-top:7px;border-radius:9px;background:rgba(255,255,255,.08);overflow:hidden}.adv-progress i{display:block;height:100%;background:#d7ba70}.adv-pill,.adv-action{border:1px solid rgba(255,255,255,.14);border-radius:999px;padding:8px 11px;background:rgba(255,255,255,.07);color:#f7f0de;font:700 10px system-ui;letter-spacing:.05em}.adv-action{background:#e0c376;color:#1f302b;border:0;padding:10px 14px}.adv-action:disabled{opacity:.4}.sighting-row{display:flex;gap:7px;margin:10px 0 7px}.sighting{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;font-weight:900;color:#23342f;border:2px solid rgba(255,255,255,.28)}
.duel-stage{text-align:center}.duel-stage h2{margin:6px 0;font:700 clamp(30px,7vw,54px)/.95 Georgia,serif}.duel-bars{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.duel-unit{text-align:left;padding:13px;border-radius:18px;background:rgba(255,255,255,.05)}.duel-unit header{display:flex;justify-content:space-between;font-size:12px}.duel-hp{height:7px;margin-top:9px;border-radius:10px;overflow:hidden;background:rgba(255,255,255,.09)}.duel-hp i{display:block;height:100%;background:#8dbf89;transition:width .35s}.duel-log{min-height:48px;padding:12px;border-radius:15px;background:rgba(0,0,0,.18);font-size:13px;line-height:1.4}.duel-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.duel-actions button{min-height:52px;border-radius:15px;border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.06);color:#fff;font-weight:750}.duel-actions button.special{background:#d9bd70;color:#20322d}.duel-actions button:disabled{opacity:.35}.boss-mark{width:76px;height:76px;margin:8px auto;border-radius:24px;display:grid;place-items:center;background:radial-gradient(circle,#e9d694,#68587f 45%,#263844 72%);box-shadow:0 0 40px rgba(194,166,233,.25);font:900 32px Georgia;color:#fff}
@media(max-width:620px){.adventure-sheet{padding:18px;border-radius:22px}.adv-grid{grid-template-columns:1fr}.ecology-chip{bottom:calc(env(safe-area-inset-bottom) + 96px);max-width:66vw;font-size:9px}.adv-stats{grid-template-columns:1fr 1fr 1fr}.duel-bars{grid-template-columns:1fr}.duel-actions{grid-template-columns:1fr 1fr 1fr}}
`;document.head.append(s)}
function buildShell(){
  const actions=document.querySelector('.utility-actions');
  if(actions&&!document.getElementById('adventure-btn')){const b=document.createElement('button');b.id='adventure-btn';b.innerHTML='<span>✦</span> Field Guide';b.onclick=openGuide;actions.append(b)}
  const chip=document.createElement('div');chip.id='ecology-chip';chip.className='ecology-chip';document.body.append(chip);
  const modal=document.createElement('section');modal.id='adventure-modal';modal.className='adventure-backdrop';modal.hidden=true;modal.setAttribute('aria-label','Field Guide');modal.innerHTML='<div class="adventure-sheet" id="adventure-sheet"></div>';modal.addEventListener('click',e=>{if(e.target===modal)closeGuide()});document.body.append(modal);
}
function closeGuide(){document.getElementById('adventure-modal').hidden=true}
function openGuide(){renderGuide();document.getElementById('adventure-modal').hidden=false}
function claimMission(id){const st=readCore(),m=MISSION_DEFS.find(x=>x.id===id);if(!st||!m||meta.claimed.includes(id)||valueFor(st,m.field)<m.goal)return;meta.claimed.push(id);meta.renown+=m.reward;meta.title=rank();writeMeta();renderGuide();pulse(false)}
function availableRival(state){const wins=Number(state?.wins)||0;return wins>=3&&wins>=meta.lastRivalAt+3}
function ecology(){const key=region(),base=ECOLOGY[key]||ECOLOGY['THE VERDANT ISLES'];const fam=[...base.families];const w=weather(),p=phase();if(w==='RAIN'&&!fam.includes(2))fam.unshift(2);if(w==='MIST'&&!fam.includes(4))fam.unshift(4);if((p==='DUSK'||p==='NIGHT')&&!fam.includes(3))fam.unshift(3);return {families:fam.slice(0,3),text:base.text}}
function renderGuide(){const st=readCore(),sheet=document.getElementById('adventure-sheet');if(!sheet)return;if(!st){sheet.innerHTML='<div class="adv-head"><div><span class="adv-kicker">FIELD GUIDE</span><h2>Begin your journey first.</h2><p>Choose a companion and enter Monterra to unlock missions, rival duels and ecology tracking.</p></div><button class="adv-close">×</button></div>';sheet.querySelector('.adv-close').onclick=closeGuide;return}
 meta.title=rank();writeMeta();const eco=ecology(),rivalReady=availableRival(st),missions=MISSION_DEFS.map(m=>{const v=valueFor(st,m.field),done=v>=m.goal,claimed=meta.claimed.includes(m.id);return `<div class="adv-mission"><div><h3>${m.title}</h3><p>${m.detail} <b>${Math.min(v,m.goal)}/${m.goal}</b></p><div class="adv-progress"><i style="width:${Math.min(100,v/m.goal*100)}%"></i></div></div>${claimed?'<span class="adv-pill">CLAIMED</span>':`<button class="adv-action" data-claim="${m.id}" ${done?'':'disabled'}>+${m.reward} RENOWN</button>`}</div>`}).join('');
 const sightings=eco.families.map(f=>`<span class="sighting" title="${FAMILY_NAMES[f]}" style="background:${FAMILY_COLOR[f]}">${FAMILY_NAMES[f][0]}</span>`).join('');
 sheet.innerHTML=`<div class="adv-head"><div><span class="adv-kicker">FIELD GUIDE · ${region()}</span><h2>${meta.title}</h2><p>Track Monterra's ecology, complete field missions and challenge roaming rivals.</p></div><button class="adv-close" aria-label="Close">×</button></div><div class="adv-stats"><div class="adv-stat"><small>RENOWN</small><strong>${meta.renown}</strong></div><div class="adv-stat"><small>RIVAL WINS</small><strong>${meta.rivalWins}</strong></div><div class="adv-stat"><small>APEX</small><strong>${meta.apexWon?'CLEARED':'LOCKED'}</strong></div></div><div class="adv-grid"><div class="adv-card"><h3>Field missions</h3>${missions}</div><div><div class="adv-card"><h3>Ecology forecast</h3><div class="sighting-row">${sightings}</div><p>${eco.text}<br><b>${phase()} · ${weather()}</b></p></div><div class="adv-card" style="margin-top:12px"><h3>Rival signal</h3><p>${rivalReady?'A roaming trainer has noticed your recent victories.':'Win three more encounters after your last rival duel to draw another challenger.'}</p><button id="rival-action" class="adv-action" style="margin-top:10px" ${rivalReady?'':'disabled'}>${rivalReady?'CHALLENGE RIVAL':'NO SIGNAL'}</button></div><div class="adv-card" style="margin-top:12px"><h3>Apex hunt</h3><p>${(st.badges?.length||0)>=6?'All six sigils resonate. Something ancient is moving beyond the mapped trails.':'Earn all six guardian sigils to reveal Monterra’s apex encounter.'}</p><button id="apex-action" class="adv-action" style="margin-top:10px" ${(st.badges?.length||0)>=6&&!meta.apexWon?'':'disabled'}>${meta.apexWon?'APEX CLEARED':'ENTER HUNT'}</button></div></div></div>`;
 sheet.querySelector('.adv-close').onclick=closeGuide;sheet.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>claimMission(b.dataset.claim));sheet.querySelector('#rival-action')?.addEventListener('click',()=>startDuel(false));sheet.querySelector('#apex-action')?.addEventListener('click',()=>startDuel(true));
}
function pulse(show){const b=document.getElementById('adventure-btn');if(!b)return;let p=b.querySelector('.adventure-pulse');if(show&&!p){p=document.createElement('i');p.className='adventure-pulse';b.append(p)}else if(!show&&p)p.remove()}
function startDuel(apex){const st=readCore();if(!st)return;const lead=leadOf(st),rival=RIVALS[meta.rivalWins%RIVALS.length],enemyFamily=apex?4:(WEAK[lead.family]??((lead.family+1)%5)),enemyLevel=Math.max(6,(Number(lead.level)||5)+(apex?6:2+Math.min(4,meta.rivalWins))),playerMax=maxHp(lead),enemyMax=apex?Math.round(playerMax*1.8):Math.round(44+enemyLevel*7+18);const battle={apex,lead,enemyFamily,enemyLevel,playerHp:playerMax,playerMax,enemyHp:enemyMax,enemyMax,energy:1,turn:0,guard:false,busy:false};renderDuel(battle,rival)}
function renderDuel(b,rival){const sheet=document.getElementById('adventure-sheet'),enemyName=b.apex?'Aetherion':`${RIVALS[meta.rivalWins%RIVALS.length].name}'s ${FAMILY_NAMES[b.enemyFamily]} partner`;sheet.innerHTML=`<div class="duel-stage">${b.apex?'<div class="boss-mark">A</div><span class="adv-kicker">APEX ENCOUNTER · PHASED BOSS</span>':`<span class="adv-kicker">RIVAL DUEL · ${rival.title.toUpperCase()}</span>`}<h2>${b.apex?'Aetherion, the Rift Warden':rival.name}</h2><p>${b.apex?'The six sigils flare. A creature unlike the island families descends into the clearing.':rival.line}</p><div class="duel-bars"><div class="duel-unit"><header><strong>Your ${FAMILY_NAMES[b.lead.family]}</strong><span>Lv. ${b.lead.level}</span></header><div class="duel-hp"><i id="duel-player-hp" style="width:${b.playerHp/b.playerMax*100}%"></i></div><small id="duel-player-label">${Math.max(0,b.playerHp)} / ${b.playerMax} HP</small></div><div class="duel-unit"><header><strong>${enemyName}</strong><span>Lv. ${b.enemyLevel}</span></header><div class="duel-hp"><i id="duel-enemy-hp" style="width:${b.enemyHp/b.enemyMax*100}%"></i></div><small id="duel-enemy-label">${Math.max(0,b.enemyHp)} / ${b.enemyMax} HP</small></div></div><div class="duel-log" id="duel-log">${b.apex?'Aetherion shifts between elemental stances every turn. Read the pattern.':'The rival waits for your opening move.'}</div><div class="duel-actions"><button id="duel-strike">STRIKE<br><small>build energy</small></button><button id="duel-special" class="special">SPECIAL<br><small id="duel-energy">energy ${b.energy}/2</small></button><button id="duel-guard">GUARD<br><small>reduce damage</small></button></div><button id="duel-exit" class="adv-pill" style="margin-top:14px">Leave challenge</button></div>`;const refresh=()=>{document.getElementById('duel-player-hp').style.width=Math.max(0,b.playerHp/b.playerMax*100)+'%';document.getElementById('duel-enemy-hp').style.width=Math.max(0,b.enemyHp/b.enemyMax*100)+'%';document.getElementById('duel-player-label').textContent=`${Math.max(0,b.playerHp)} / ${b.playerMax} HP`;document.getElementById('duel-enemy-label').textContent=`${Math.max(0,b.enemyHp)} / ${b.enemyMax} HP`;document.getElementById('duel-energy').textContent=`energy ${b.energy}/2`;document.getElementById('duel-special').disabled=b.energy<2||b.busy;document.getElementById('duel-strike').disabled=b.busy;document.getElementById('duel-guard').disabled=b.busy};const act=kind=>duelTurn(b,kind,refresh,rival);document.getElementById('duel-strike').onclick=()=>act('strike');document.getElementById('duel-special').onclick=()=>act('special');document.getElementById('duel-guard').onclick=()=>act('guard');document.getElementById('duel-exit').onclick=()=>renderGuide();refresh()}
async function duelTurn(b,kind,refresh,rival){if(b.busy)return;b.busy=true;const log=document.getElementById('duel-log'),special=kind==='special';if(special&&b.energy<2){b.busy=false;refresh();return}if(kind==='guard'){b.guard=true;b.energy=Math.min(2,b.energy+1);log.textContent='You brace and study the opponent. Energy gained.'}else{b.energy=special?0:Math.min(2,b.energy+1);const base=(8+(Number(b.lead.level)||5)*1.35+(Number(b.lead.stage)||0)*3)*(special?1.7:1);let enemyType=b.enemyFamily;if(b.apex)enemyType=(b.enemyFamily+b.turn)%5;const hit=Math.max(5,Math.round(base*typeEffect(b.lead.family,enemyType)*(.92+Math.random()*.16)));b.enemyHp-=hit;log.textContent=`${special?'Signature attack':'Quick strike'} lands for ${hit}. ${typeEffect(b.lead.family,enemyType)>1?'The stance was vulnerable.':''}`}refresh();await new Promise(r=>setTimeout(r,450));if(b.enemyHp<=0){finishDuel(b,true,rival);return}const heavy=b.turn%3===2,enemyBase=(7+b.enemyLevel*1.22)*(heavy?1.55:1)*(b.apex?1.12:1);const hit=Math.max(4,Math.round(enemyBase*typeEffect(b.enemyFamily,b.lead.family)*(b.guard?.35:1)*(.9+Math.random()*.18)));b.guard=false;b.playerHp-=hit;b.turn++;log.textContent+=` ${b.apex?'Aetherion':'The rival'} answers${heavy?' with a heavy attack':''} for ${hit}.`;refresh();await new Promise(r=>setTimeout(r,400));if(b.playerHp<=0){finishDuel(b,false,rival);return}b.busy=false;refresh()}
function finishDuel(b,won,rival){const sheet=document.getElementById('adventure-sheet');if(won){if(b.apex){meta.apexWon=true;meta.renown+=300;meta.title='Apex Warden'}else{meta.rivalWins++;meta.lastRivalAt=Number(readCore()?.wins)||meta.lastRivalAt;meta.renown+=65;meta.title=rank()}writeMeta()}sheet.innerHTML=`<div class="duel-stage">${b.apex?'<div class="boss-mark">A</div>':''}<span class="adv-kicker">${won?'CHALLENGE COMPLETE':'CHALLENGE LOST'}</span><h2>${won?(b.apex?'The rift goes quiet.':'Rival defeated.'):'The wilds push back.'}</h2><p>${won?(b.apex?'Aetherion acknowledges the six sigils. You have completed Monterra’s current apex hunt and earned 300 renown.':`${rival.name} yields the trail. +65 renown.`):'Your core adventure is unchanged. Recover, evolve and return with a stronger plan.'}</p><button id="duel-done" class="adv-action" style="margin-top:18px">BACK TO FIELD GUIDE</button></div>`;sheet.querySelector('#duel-done').onclick=renderGuide;pulse(true)}
function updateChip(){const st=readCore(),chip=document.getElementById('ecology-chip');if(!chip)return;if(!st){chip.textContent='FIELD GUIDE UNLOCKS AFTER YOU BEGIN';return}const eco=ecology();chip.textContent=`${region()} · LIKELY SIGHTINGS: ${eco.families.map(f=>FAMILY_NAMES[f].toUpperCase()).join(' / ')}`;const claimable=MISSION_DEFS.some(m=>!meta.claimed.includes(m.id)&&valueFor(st,m.field)>=m.goal);pulse(claimable||availableRival(st)||((st.badges?.length||0)>=6&&!meta.apexWon))}
injectStyle();buildShell();updateChip();setInterval(updateChip,1800);document.addEventListener('visibilitychange',()=>{if(!document.hidden){meta=readMeta();updateChip()}});
