import {Renderer,Batch,clamp,mix} from './engine.js';
import {FAMILIES,VERSION,SAVE_KEY,member,freshState,normalize,nameOf,maxHp,xpNeeded,canEvolve,gainXp,evolve,damage,captureChance,healthyIndex,effectiveness} from './core.js';
import {creature,trainer} from './creatures.js';
import {makeWorld,height,walkable,zone,CAMP,GUARDIANS} from './world.js';
const $=id=>document.getElementById(id);
const ui=Object.fromEntries([...document.querySelectorAll('[id]')].map(el=>[el.id,el]));
let storageAvailable=true;
function readSave(){try{return normalize(JSON.parse(localStorage.getItem(SAVE_KEY)||localStorage.getItem('monterra-wilds-save-v2')||'null'));}catch{return null;}}
let state=readSave(),mode='intro',selectedFamily=state?.team[state.active]?.family||0,renderer,world;
let currentBattle=null,evolution=null,previousMode='explore',near=null,targetPoint=null,yaw=0,time=0,toastTimer=0,saveClock=0,stepsClock=0,drawClock=0,roll=Math.random;
const batch=new Batch(),keys=new Set(),stickInput={x:0,y:0,id:null},allyPosition={x:0,z:9.5},particles=[];
let renderPaused=false;
let audio=null,lastSound=0,animation=null,lastFrame=performance.now(),frames=0,fps=0,frameWindow=performance.now();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function save(){if(!state)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;$('save-note').textContent='Browser storage is unavailable. You can still play, but progress will not survive closing this page.';}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
function setMode(next){mode=next;document.body.dataset.mode=next;$('intro').hidden=next!=='intro';$('explore-ui').hidden=!['explore','team'].includes(next);$('battle-ui').hidden=!['battle','result'].includes(next);$('team-panel').hidden=next!=='team';$('evolution-ui').hidden=next!=='evolution';$('help-panel').hidden=next!=='help';$('help-btn').disabled=['battle','result','evolution'].includes(next);if(next!=='explore'){targetPoint=null;releaseStick();keys.clear();$('near-label').hidden=true;}if(next==='explore'){syncHud();save();}}
function lead(){return state.team[state.active];}
function sound(notes=[440],length=.12,kind='sine'){if(state?.muted!==false)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});notes.forEach((freq,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime+i*.08;osc.type=kind;osc.frequency.setValueAtTime(freq,t);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.045,t+.01);gain.gain.exponentialRampToValueAtTime(.0001,t+length);osc.connect(gain);gain.connect(audio.destination);osc.start(t);osc.stop(t+length+.03);});}catch{/* Sound is optional. */}}
function syncSound(){$('sound-btn').setAttribute('aria-pressed',String(state?.muted===false));$('sound-btn').setAttribute('aria-label',state?.muted===false?'Turn sound off':'Turn sound on');}
function syncHud(){if(!state)return;const m=lead();$('orb-count').textContent=state.orbs;$('potion-count').textContent=state.potions;$('partner-name').textContent=nameOf(m);$('partner-level').textContent=`Lv. ${m.level}`;$('partner-type').textContent=FAMILIES[m.family].type[0];$('partner-type').style.background=FAMILIES[m.family].color;$('partner-hp').style.width=`${m.hp/maxHp(m)*100}%`;$('partner-xp').style.width=`${m.xp/xpNeeded(m)*100}%`;$('partner-progress').textContent=canEvolve(m)?'Ready to evolve! Open Team.':`${m.xp} / ${xpNeeded(m)} XP ${m.stage<2?' | Evolves at Lv. '+(m.stage===0?7:12):' | Final form'}`;$('sigil-count').textContent=`${state.badges.length} / 3 SIGILS`;
 const next=GUARDIANS[state.badges.length];if(!state.catches){$('quest-title').textContent='A friendship in the wild';$('quest-detail').textContent='Approach a creature. Weaken it, then use a capture orb.';}else if(next){$('quest-title').textContent=next.title;$('quest-detail').textContent=`Follow the gold map marker. Earn the ${next.badge.toLowerCase()}.`;}else{$('quest-title').textContent='Guardian of the wilds';$('quest-detail').textContent='All three sigils earned! Discover every creature and evolution.';}syncSound();}
function updateStarter(){const root=$('starter-options');root.replaceChildren();for(const f of [0,1,2]){const b=document.createElement('button');b.className=`starter-option${selectedFamily===f?' selected':''}`;b.setAttribute('aria-pressed',String(selectedFamily===f));b.innerHTML=`<span class="seed" style="background:${FAMILIES[f].color}"></span><strong>${FAMILIES[f].names[0]}</strong><small>${FAMILIES[f].type.toUpperCase()}</small>`;b.onclick=()=>{selectedFamily=f;updateStarter();};root.append(b);}$('starter-description').textContent=state?`Welcome back. Your ${nameOf(lead())} and ${state.team.length-1} other companion${state.team.length===2?'':'s'} are waiting.`:FAMILIES[selectedFamily].description;$('intro-caption').replaceChildren(document.createTextNode(FAMILIES[selectedFamily].names[0].toUpperCase()));const s=document.createElement('small');s.textContent=FAMILIES[selectedFamily].type.toUpperCase()+' COMPANION';$('intro-caption').append(s);$('start-btn').innerHTML=state?'Continue your journey <span>&#8599;</span>':'Begin adventure <span>&#8599;</span>';$('starter-title').textContent=state?'YOUR ADVENTURE IS WAITING':'CHOOSE YOUR FIRST COMPANION';root.hidden=Boolean(state);}
function start(){if(!state){state=freshState(selectedFamily);state.muted=true;}if(!walkable(state.position.x,state.position.z))state.position={...CAMP};if(lead().hp<=0){const healthy=healthyIndex(state);if(healthy>=0)state.active=healthy;else state.team.forEach(m=>m.hp=maxHp(m));}allyPosition.x=state.position.x-1.3;allyPosition.z=state.position.z+1.3;setMode('explore');toast('Welcome to the wilds. Approach a creature to make your first friend.');sound([392,494,587],.2);}
const spawnDefinitions=[[3,4,4,4],[1,-5,2,3],[0,-8,-6,4],[2,10,-2,4],[4,12,-13,6],[1,-17,-10,5],[3,-10,13,5],[0,5,-17,6],[2,24,9,5],[4,-8,-22,7],[3,18,-18,8],[1,-23,2,6]];
const roamers=spawnDefinitions.map(([family,x,z,level],id)=>({id,family,stage:level>=7?1:0,level,x,z,bx:x,bz:z,yaw:0,alive:true,cooldown:0}));
function collision(x,z){return !walkable(x,z)||world.obstacles.some(o=>Math.hypot(x-o.x,z-o.z)<o.r+.27);}
function movePlayer(dt){if(mode!=='explore'||!state)return false;let dx=0,dz=0;const sx=stickInput.x+(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),sy=stickInput.y+(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);
 if(sx||sy){targetPoint=null;dx=sx*.8+sy*.6;dz=-sx*.6+sy*.8;}else if(targetPoint){dx=targetPoint.x-state.position.x;dz=targetPoint.z-state.position.z;if(Math.hypot(dx,dz)<.3){targetPoint=null;dx=dz=0;}}
 const distance=Math.hypot(dx,dz);if(distance>.03){const speed=5.0*dt/Math.max(1,distance);dx*=speed;dz*=speed;const p=state.position;if(!collision(p.x+dx,p.z))p.x+=dx;if(!collision(p.x,p.z+dz))p.z+=dz;yaw=Math.atan2(dx,dz);saveClock+=dt;stepsClock+=dt;if(saveClock>2){saveClock=0;save();}if(stepsClock>1){stepsClock=0;state.steps++;}return true;}return false;}
function findNear(){if(mode!=='explore')return;const p=state.position,list=[];for(const w of roamers.filter(w=>w.alive))list.push({kind:'wild',value:w,x:w.x,z:w.z,d:Math.hypot(p.x-w.x,p.z-w.z),name:nameOf(w),label:'ENCOUNTER'});GUARDIANS.forEach((g,id)=>{if(!state.badges.includes(id))list.push({kind:'guardian',value:id,x:g.x,z:g.z,d:Math.hypot(p.x-g.x,p.z-g.z),name:g.title,label:'CHALLENGE'});});if(Math.hypot(p.x-CAMP.x,p.z-CAMP.z)<3.1)list.push({kind:'camp',x:CAMP.x,z:CAMP.z,d:0,name:'Explorer camp',label:'REST & HEAL'});
 near=list.sort((a,b)=>a.d-b.d)[0];const ready=near&&near.d<4.5;$('interact-btn').classList.toggle('ready',!!ready);$('interact-label').textContent=ready?near.label:'EXPLORE';$('interact-icon').textContent=ready?'\u2726':'\u25c7';
 if(near&&near.d<8){const h=height(near.x,near.z),point=renderer.project([near.x,h+2.4,near.z]);$('near-label').hidden=false;$('near-label').textContent=near.name+(near.kind==='wild'?` | Lv. ${near.value.level}`:'');$('near-label').style.left=`${point[0]*innerWidth}px`;$('near-label').style.top=`${point[1]*innerHeight}px`;}else $('near-label').hidden=true;
 $('region').textContent=zone(p.x,p.z).toUpperCase();}
function interact(){if(mode!=='explore')return;if(!near||near.d>=4.5){toast('Move closer to a roaming creature, a guardian gate, or camp.');return;}if(near.kind==='camp'){rest(false);return;}if(near.kind==='guardian'){const id=near.value;if(state.badges.length<id){toast('Earn the earlier guardian sigils first. Follow the gold map marker.');return;}beginBattle({...member(GUARDIANS[id].family,GUARDIANS[id].level,Math.min(2,id+1)),guardian:id});}else beginBattle({...member(near.value.family,near.value.level,near.value.stage),spawnId:near.value.id});}
function rest(teleport=true){if(mode!=='explore')return;if(teleport){state.position={...CAMP};allyPosition.x=CAMP.x-1.2;allyPosition.z=CAMP.z+1.2;targetPoint=null;}state.team.forEach(m=>m.hp=maxHp(m));state.orbs=Math.max(12,state.orbs);state.potions=Math.max(5,state.potions);syncHud();save();toast('Rested! Team healed, orbs and potions restocked.');sound([330,440,660],.18);}
function beginBattle(opponent){if(mode!=='explore')return;if(lead().hp<=0){toast('Your companion needs rest. Tap Camp to heal.');return;}currentBattle={opponent,busy:false,charge:1,turn:0,token:Symbol(),finished:false};animation=null;setMode('battle');$('battle-kicker').textContent=opponent.guardian!==undefined?'GUARDIAN CHALLENGE':'WILD ENCOUNTER';$('battle-title').textContent=opponent.guardian!==undefined?GUARDIANS[opponent.guardian].title:`Meet ${nameOf(opponent)}`;$('battle-log').textContent=opponent.guardian!==undefined?'Win this battle to earn a guardian sigil. Guardians cannot be captured.':'A wild companion! Weaken it before throwing an orb.';$('battle-continue').hidden=true;document.querySelector('.move-grid').hidden=false;syncBattle();sound([294,392],.15);}
function syncBattle(){if(!currentBattle)return;const o=currentBattle.opponent,a=lead();for(const [prefix,m] of [['enemy',o],['ally',a]]){$(`${prefix}-name`).textContent=nameOf(m);$(`${prefix}-level`).textContent=`Lv. ${m.level}`;$(`${prefix}-type`).textContent=`${FAMILIES[m.family].type} | ${m.stage===2?'Final form':'Form '+(m.stage+1)}`;$(`${prefix}-hp`).style.width=`${Math.max(0,m.hp)/maxHp(m)*100}%`;$(`${prefix}-hp`).style.background=m.hp/maxHp(m)<.3?'#d48c71':'#81a772';$(`${prefix}-health`).textContent=`${Math.max(0,m.hp)} / ${maxHp(m)} HP`;}
 $('special-name').textContent=FAMILIES[a.family].move;$('charge-label').textContent=`Energy ${currentBattle.charge} / 2`;$('capture-label').textContent=o.guardian!==undefined?'Guardian: not catchable':`${state.orbs} left | ${Math.round(captureChance(o)*100)}% chance`;$('heal-label').textContent=`${state.potions} potion${state.potions===1?'':'s'} left`;
 const disabled=currentBattle.busy||currentBattle.finished||mode!=='battle';$('strike-btn').disabled=disabled;$('special-btn').disabled=disabled||currentBattle.charge<2;$('capture-btn').disabled=disabled||state.orbs<1||o.guardian!==undefined||state.team.length>=60;$('heal-btn').disabled=disabled||state.potions<1||a.hp>=maxHp(a);$('run-btn').disabled=currentBattle.busy||currentBattle.finished;}
function floatDamage(amount,side){const p=renderer.project([side==='enemy'?113:107,2.2,0]);$('damage-float').hidden=false;$('damage-float').textContent=amount;$('damage-float').style.left=p[0]*innerWidth+'px';$('damage-float').style.top=p[1]*innerHeight+'px';$('damage-float').style.animation='none';void $('damage-float').offsetWidth;$('damage-float').style.animation='';setTimeout(()=>$('damage-float').hidden=true,800);}
function burst(p,col,n=24){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,r=.8+Math.random()*2.5;particles.push({p:[...p],v:[Math.cos(a)*r,1+Math.random()*3,Math.sin(a)*r],life:.6+Math.random()*.7,max:1.3,color:col});}}
async function action(kind){const b=currentBattle;if(mode!=='battle'||!b||b.busy||b.finished)return;const o=b.opponent,a=lead();if(kind==='special'&&b.charge<2||kind==='capture'&&(state.orbs<1||o.guardian!==undefined||state.team.length>=60)||kind==='heal'&&(state.potions<1||a.hp>=maxHp(a)))return;b.busy=true;syncBattle();
 if(kind==='heal'){state.potions--;const amount=Math.min(maxHp(a)-a.hp,Math.round(maxHp(a)*.65));a.hp+=amount;$('battle-log').textContent=`${nameOf(a)} recovered ${amount} HP.`;burst([107,1,0],'#b9e5a1');sound([440,660,880],.16);floatDamage('+'+amount,'ally');save();syncBattle();await sleep(650);}
 else if(kind==='capture'){state.orbs--;save();animation={kind:'capture',start:time,duration:1.05};$('battle-log').textContent='One throw. A new friendship?';sound([660,523,392],.13);await sleep(1150);if(currentBattle!==b||mode!=='battle')return;if(roll()<captureChance(o)){state.team.push(member(o.family,o.level,o.stage));state.catches++;gainXp(a,24);burst([113,1,0],'#fbe8ad',40);finishBattle('caught',`${nameOf(o)} joined your team! +24 XP.`);return;}$('battle-log').textContent=`${nameOf(o)} broke free. Lower its health to improve your chances.`;sound([220,196],.16);await sleep(600);}
 else {const special=kind==='special';b.charge=special?0:Math.min(2,b.charge+1);animation={kind:special?'special':'strike',side:'ally',start:time,duration:.58};$('battle-log').textContent=`${nameOf(a)} used ${special?FAMILIES[a.family].move:'Quick strike'}!`;sound(special?[220,440,880]:[330,220],.13,special?'triangle':'sine');await sleep(440);if(currentBattle!==b||mode!=='battle')return;const hit=damage(a,o,special,roll);o.hp=Math.max(0,o.hp-hit);floatDamage('-'+hit,'enemy');burst([113,1,0],FAMILIES[a.family].color,special?30:14);$('battle-log').textContent=`${hit} damage.${effectiveness(a,o)>1?' Super effective!':effectiveness(a,o)<1?' The wild creature resisted some damage.':''}`;syncBattle();if(o.hp<=0){const levels=gainXp(a,o.guardian!==undefined?120:72);state.wins++;state.orbs+=2;if(o.guardian!==undefined&&!state.badges.includes(o.guardian)){state.badges.push(o.guardian);state.potions+=2;}finishBattle('victory',`${o.guardian!==undefined?GUARDIANS[o.guardian].badge+' earned!':'Victory! +72 XP, +2 orbs.'}${levels?' '+nameOf(a)+' reached Lv. '+a.level+'.':''}`);return;}await sleep(520);}
 if(currentBattle!==b||mode!=='battle')return;animation={kind:'strike',side:'enemy',start:time,duration:.48};$('battle-log').textContent=`${nameOf(o)} strikes back!`;await sleep(370);if(currentBattle!==b||mode!=='battle')return;const hit=damage(o,lead(),false,roll);lead().hp=Math.max(0,lead().hp-hit);floatDamage('-'+hit,'ally');burst([107,1,0],'#ead5ae',12);sound([150],.15);b.turn++;save();if(lead().hp<=0){const next=healthyIndex(state);if(next<0){finishBattle('lost','Your team needs rest. Return to camp to recover, with no lost companions.');return;}state.active=next;b.charge=1;$('battle-log').textContent=`Your partner needs rest. ${nameOf(lead())} steps in!`;}else{$('battle-log').textContent=`${nameOf(lead())} took ${hit} damage. Choose your next move.`;}b.busy=false;syncBattle();save();}
function finishBattle(result,message){const b=currentBattle;b.finished=true;b.busy=false;b.result=result;if(result!=='lost'&&b.opponent.spawnId!==undefined){const w=roamers[b.opponent.spawnId];w.alive=false;w.cooldown=80;}save();setMode('result');$('battle-log').textContent=message+(result!=='lost'&&canEvolve(lead())?' Your companion is ready to evolve!':'');$('battle-title').textContent=result==='caught'?'A new friendship.':result==='lost'?'A chance to grow.':'A little stronger, together.';document.querySelector('.move-grid').hidden=true;$('battle-continue').hidden=false;$('battle-continue').textContent=result==='lost'?'Rest at camp':canEvolve(lead())?'Discover your evolution':'Back to the wilds';syncBattle();sound(result==='lost'?[262,220]:[392,494,587,784],.22);}
function continueBattle(){if(mode!=='result'||!currentBattle)return;const lost=currentBattle.result==='lost';currentBattle=null;if(lost){setMode('explore');rest(true);}else if(canEvolve(lead()))openEvolution(state.active);else setMode('explore');}
function run(){if(mode!=='battle'||!currentBattle||currentBattle.busy)return;currentBattle=null;setMode('explore');toast('You left the encounter. Your companions are safe.');}
function openTeam(){if(mode!=='explore')return;setMode('team');renderTeam();}
function renderTeam(){const list=$('team-list');list.replaceChildren();$('team-count').textContent=state.team.length;state.team.forEach((m,i)=>{const row=document.createElement('article');row.className='team-row';row.innerHTML=`<div class="team-badge" style="background:${FAMILIES[m.family].color}">${FAMILIES[m.family].type[0]}</div><div class="team-details"><strong>${nameOf(m)}${i===state.active?' <small>LEAD</small>':''}</strong><p>${FAMILIES[m.family].type} | Lv. ${m.level} | Form ${m.stage+1}/3</p><p>${m.hp}/${maxHp(m)} HP | ${m.xp}/${xpNeeded(m)} XP</p><div class="health-track"><i style="width:${m.hp/maxHp(m)*100}%"></i></div></div><div class="team-buttons"></div>`;const buttons=row.querySelector('.team-buttons'),select=document.createElement('button');select.textContent=i===state.active?'Leading':m.hp<=0?'Needs rest':'Make lead';select.disabled=i===state.active||m.hp<=0;select.onclick=()=>{state.active=i;syncHud();save();renderTeam();};buttons.append(select);if(canEvolve(m)){const ev=document.createElement('button');ev.className='evolve-btn';ev.textContent='Evolve';ev.onclick=()=>openEvolution(i);buttons.append(ev);}list.append(row);});const forms=new Set(state.team.map(m=>m.family+':'+m.stage));$('collection-progress').textContent=`${forms.size} distinct forms in your team | ${state.catches} captures | ${state.wins} victories | ${state.badges.length}/3 guardian sigils`;}
function openEvolution(index){const m=state.team[index];if(!canEvolve(m))return;evolution={index,oldName:nameOf(m),phase:'ready',start:0};setMode('evolution');$('evolution-title').textContent=`${nameOf(m)} is ready.`;$('evolution-description').textContent=`Your bond is growing. A new form, ${FAMILIES[m.family].names[m.stage+1]}, is waiting.`;$('evolution-btn').disabled=false;$('evolution-btn').textContent='Evolve now';$('later-btn').hidden=false;}
async function evolveNow(){if(mode!=='evolution'||!evolution)return;if(evolution.phase==='complete'){evolution=null;setMode('explore');return;}if(evolution.phase!=='ready')return;const ev=evolution,m=state.team[ev.index];ev.phase='animating';ev.start=time;$('evolution-btn').disabled=true;$('later-btn').hidden=true;$('evolution-title').textContent='Something extraordinary...';$('evolution-description').textContent='Every adventure changes you.';sound([262,330,392,523,660,784,1046],.45);await sleep(2000);if(evolution!==ev)return;evolve(m);save();burst([110,2,0],FAMILIES[m.family].color,80);await sleep(1200);if(evolution!==ev)return;ev.phase='complete';$('evolution-title').textContent=`Hello, ${nameOf(m)}.`;$('evolution-description').textContent=`${ev.oldName} evolved into ${nameOf(m)}. Stronger stats. A whole new look.`;$('evolution-btn').disabled=false;$('evolution-btn').textContent='Keep the adventure going';sound([392,523,660,784],.35);}
function map(){if(!state)return;const c=$('minimap'),ctx=c.getContext('2d'),scale=2.1;ctx.clearRect(0,0,160,160);ctx.fillStyle='#7dafae';ctx.fillRect(0,0,160,160);ctx.fillStyle='#adc397';ctx.beginPath();ctx.arc(80,80,69,0,7);ctx.fill();ctx.fillStyle='#8cbdc4';ctx.beginPath();ctx.ellipse(80+19*scale,80,7.8*scale,6.2*scale,0,0,7);ctx.fill();ctx.strokeStyle='#e2d6ae';ctx.lineWidth=5;ctx.beginPath();for(let z=-30;z<31;z++){ctx.lineTo(80+3*Math.sin(z*.14)*scale,80+z*scale);}ctx.stroke();for(const w of roamers.filter(w=>w.alive)){ctx.fillStyle='#648969';ctx.beginPath();ctx.arc(80+w.x*scale,80+w.z*scale,1.7,0,7);ctx.fill();}for(let i=0;i<3;i++){const g=GUARDIANS[i];ctx.fillStyle=state.badges.includes(i)?'#719a8c':i===state.badges.length?'#dcae4f':'#a1a68a';ctx.beginPath();ctx.arc(80+g.x*scale,80+g.z*scale,i===state.badges.length?4.2:3,0,7);ctx.fill();}ctx.fillStyle='#fff4c8';ctx.fillRect(77,80+8*scale-3,6,6);ctx.fillStyle='#ffffff';ctx.strokeStyle='#355c49';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(80+state.position.x*scale,80+state.position.z*scale,4,0,7);ctx.fill();ctx.stroke();}
function releaseStick(){stickInput.x=stickInput.y=0;stickInput.id=null;if($('stick'))$('stick').style.transform='';}
function updateStick(e){const rect=$('joystick').getBoundingClientRect(),x=e.clientX-(rect.left+rect.width/2),y=e.clientY-(rect.top+rect.height/2),r=Math.hypot(x,y),limit=rect.width*.33,factor=r>limit?limit/r:1;stickInput.x=x*factor/limit;stickInput.y=y*factor/limit;$('stick').style.transform=`translate(${x*factor}px,${y*factor}px)`;}
$('joystick').addEventListener('pointerdown',e=>{if(mode!=='explore')return;e.preventDefault();stickInput.id=e.pointerId;$('joystick').setPointerCapture(e.pointerId);updateStick(e);});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===stickInput.id)updateStick(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(event,releaseStick);
let tapStart=null;$('world').addEventListener('pointerdown',e=>{if(mode==='explore')tapStart={x:e.clientX,y:e.clientY};});$('world').addEventListener('pointerup',e=>{if(mode!=='explore'||!tapStart||Math.hypot(e.clientX-tapStart.x,e.clientY-tapStart.y)>12)return;tapStart=null;const p=renderer.groundPoint(e.clientX,e.clientY);if(p&&walkable(...p))targetPoint={x:p[0],z:p[1]};});
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){if(mode==='explore'){keys.add(e.key);e.preventDefault();}}if(e.repeat)return;if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='t')openTeam();if(e.key==='Escape'){if(mode==='team')setMode('explore');if(mode==='help')setMode(previousMode);}});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>{keys.clear();releaseStick();save();});document.addEventListener('visibilitychange',()=>{keys.clear();releaseStick();save();lastFrame=performance.now();});addEventListener('pagehide',save);
$('start-btn').onclick=start;$('team-btn').onclick=openTeam;$('close-team').onclick=()=>setMode('explore');$('camp-btn').onclick=()=>rest(true);$('interact-btn').onclick=interact;$('strike-btn').onclick=()=>action('strike');$('special-btn').onclick=()=>action('special');$('capture-btn').onclick=()=>action('capture');$('heal-btn').onclick=()=>action('heal');$('battle-continue').onclick=continueBattle;$('run-btn').onclick=run;$('evolution-btn').onclick=evolveNow;$('later-btn').onclick=()=>{if(evolution?.phase==='ready'){evolution=null;setMode('explore');}};$('help-btn').onclick=()=>{if(['battle','result','evolution'].includes(mode))return;previousMode=mode;setMode('help');};$('close-help').onclick=()=>setMode(previousMode);$('sound-btn').onclick=()=>{if(!state){toast('Start your journey to enable sound.');return;}state.muted=!state.muted;syncSound();save();sound([440,554],.14);};$('restart-btn').onclick=()=>{if(!confirm('Start a new journey? This replaces your Monterra team and progress on this browser.'))return;try{localStorage.removeItem(SAVE_KEY);localStorage.removeItem('monterra-wilds-save-v2');}catch{}state=null;selectedFamily=0;currentBattle=null;evolution=null;roamers.forEach(w=>{w.alive=true;w.cooldown=0;});updateStarter();setMode('intro');};
function updateCamera(dt){const portrait=innerWidth/innerHeight<.85;let target,eye;if(['battle','result'].includes(mode)){const d=portrait?1.38:1;target=[110,1.0,0];eye=[110+10*d,7.6*d,13.8*d];}else if(mode==='evolution'){target=[110,1.35,0];eye=[114.8,4.4,8.5];}else if(mode==='intro'||mode==='help'&&previousMode==='intro'){target=portrait?[110,1.8,0]:[107.7,1.4,0];eye=portrait?[115,5.7,9.2]:[117,6.2,12.8];}else{const p=state.position;const d=portrait?1.18:1;target=[p.x,height(p.x,p.z)+.4,p.z];eye=[p.x+12*d,16.5*d,p.z+16*d];}const rate=1-Math.exp(-dt*4.2);renderer.eye=renderer.eye.map((v,i)=>mix(v,eye[i],rate));renderer.target=renderer.target.map((v,i)=>mix(v,target[i],rate));}
function addArena(){const b=world.batch;b.add('cylinder',[110,-.25,0],[15,.4,15],'#8ba77e');b.add('cylinder',[110,.165,0],[6.7,.015,4.8],'#a4b68c');for(const x of [107,113])b.add('cylinder',[x,.2,0],[1.65,.02,1.65],'#c4cba5');for(let i=0;i<13;i++){const a=i/13*Math.PI*2,x=110+Math.cos(a)*12,z=Math.sin(a)*12,s=1.2+(i%3)*.4;if(z>6)continue;b.add('cylinder',[x,1.3,z],[.18,1.3,.18],'#7b755d');b.add('low',[x,4.1,z],[s*1.45,s*1.6,s*1.4],i%2?'#74986f':'#557f65');b.add('low',[x+.65,4.6,z+.2],[s,s,s],'#94b77e');}for(let i=0;i<20;i++){const x=102+(i*2.7)%16,z=-4-(i%4);b.add('sphere',[x,.45,z],[.16,.14,.16],i%2?'#f0d594':'#ebbac4');b.add('cylinder',[x,.27,z],[.025,.19,.025],'#7d9569');}}
function drawDynamic(dt,moving){batch.reset();const cinematic=['battle','result','evolution','intro'].includes(mode)||mode==='help'&&previousMode==='intro';
 if(mode==='intro'||mode==='help'&&previousMode==='intro'){creature(batch,{family:selectedFamily,stage:0},[110,.2,0],.4,innerWidth/innerHeight<.85?1.4:1.85,time,false);}
 else if(mode==='evolution'&&evolution){const m=state.team[evolution.index],progress=evolution.phase==='animating'?time-evolution.start:0,glow=evolution.phase==='animating'&&progress<2.3;creature(batch,m,[110,.2+Math.sin(progress*3)*.06,0],.4+(glow?progress*2:0),1.65+(glow?Math.sin(progress*11)*.04:0),time,false,glow);if(glow){for(let i=0;i<12;i++){const a=time*2+i/12*Math.PI*2;batch.add('gem',[110+Math.cos(a)*2.1,.5+(time*2+i*.3)%3,Math.sin(a)*2.1],[.07,.18,.07],'#fff0b3');}}}
 else if(['battle','result'].includes(mode)&&currentBattle){const a=lead(),o=currentBattle.opponent;let ax=107,ox=113;const anim=animation&&(time-animation.start)/animation.duration;if(animation&&anim>=0&&anim<1){if(animation.kind==='strike'||animation.kind==='special'){const lunge=Math.sin(anim*Math.PI)*1.1;if(animation.side==='ally')ax+=lunge;else ox-=lunge;}if(animation.kind==='capture'){batch.add('sphere',[mix(107,113,anim),1+Math.sin(anim*Math.PI)*2,0],[.23,.23,.23],'#fff0c1');batch.add('sphere',[mix(107,113,anim),1+Math.sin(anim*Math.PI)*2+.10,0],[.23,.12,.23],'#69977b');}}
 creature(batch,a,[ax,.24,0],Math.PI/2,1.15,time,false);if(!(mode==='result'&&currentBattle.result==='caught'))creature(batch,o,[ox,.24,0],-Math.PI/2,1.15,time+.7,false);}
 else if(state){const p=state.position;trainer(batch,[p.x,height(p.x,p.z),p.z],yaw,time,moving);const dist=Math.hypot(p.x-allyPosition.x,p.z-allyPosition.z);if(mode==='explore'&&dist>1.6){const f=Math.min(1,dt*4);allyPosition.x=mix(allyPosition.x,p.x-1.0,f);allyPosition.z=mix(allyPosition.z,p.z+1.0,f);}creature(batch,lead(),[allyPosition.x,height(allyPosition.x,allyPosition.z),allyPosition.z],Math.atan2(p.x-allyPosition.x,p.z-allyPosition.z),.69,time,dist>2&&moving);
 const visible=roamers.filter(w=>w.alive&&Math.hypot(w.x-p.x,w.z-p.z)<18).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z)).slice(0,4);for(const w of visible)creature(batch,w,[w.x,height(w.x,w.z),w.z],w.yaw,.85,time+w.id,true);
 for(let i=0;i<GUARDIANS.length;i++){const g=GUARDIANS[i];if(Math.hypot(g.x-p.x,g.z-p.z)<20&&!state.badges.includes(i)){creature(batch,{family:g.family,stage:Math.min(2,i+1)},[g.x,height(g.x,g.z)+.12,g.z],Math.PI*.12,1.07,time+i);batch.add('gem',[g.x,height(g.x,g.z)+3.2+Math.sin(time)*.12,g.z],[.15,.23,.15],'#f5daa1');}}
 for(const pick of world.pickups)if(pick.active&&Math.hypot(pick.x-p.x,pick.z-p.z)<17){const y=height(pick.x,pick.z)+.65+Math.sin(time*2+pick.x)*.12;batch.add('gem',[pick.x,y,pick.z],[.17,.23,.17],'#fff0b0',[0,time,0]);if(mode==='explore'&&Math.hypot(pick.x-p.x,pick.z-p.z)<1){pick.active=false;pick.timer=50;state.orbs+=3;syncHud();save();toast('+3 capture orbs');sound([660,880],.12);}}
 if(targetPoint&&mode==='explore'){batch.add('cylinder',[targetPoint.x,height(targetPoint.x,targetPoint.z)+.04,targetPoint.z],[.24,.015,.24],'#f5e4ab');}
 }
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue;}p.p=p.p.map((v,i)=>v+p.v[i]*dt);p.v[1]-=dt*2.2;const s=.055*p.life/p.max;batch.add('gem',p.p,[s,s,s],p.color);}
 if(!cinematic){const crystalY=height(.6,7)+1.1+Math.sin(time*1.5)*.12;batch.add('gem',[.6,crystalY,7],[.32,.5,.32],'#b8ecd7',[0,time*.35,0]);}
}
function tick(now){if(renderPaused){lastFrame=now;requestAnimationFrame(tick);return;}const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;time+=dt;const moving=movePlayer(dt);if(mode==='explore'){for(const w of roamers){if(!w.alive){w.cooldown-=dt;if(w.cooldown<=0)w.alive=true;continue;}const x=w.bx+Math.sin(time*.2+w.id)*1.1,z=w.bz+Math.cos(time*.23+w.id)*1.0;if(walkable(x,z)){w.yaw=Math.atan2(x-w.x,z-w.z);w.x=x;w.z=z;}}for(const pick of world.pickups)if(!pick.active){pick.timer-=dt;if(pick.timer<=0)pick.active=true;}if(state?.muted===false&&time-lastSound>7){lastSound=time;sound([[262,330,392][Math.floor(roll()*3)]],.7);}}
 updateCamera(dt);drawDynamic(dt,moving);renderer.render(batch);drawClock+=dt;if(drawClock>.12){drawClock=0;if(mode==='explore'){findNear();map();syncHud();}}frames++;if(now-frameWindow>1000){fps=frames*1000/(now-frameWindow);frames=0;frameWindow=now;}requestAnimationFrame(tick);}
function fail(error){$('loading').hidden=false;$('load-message').textContent=error.message||'The game could not start. Please reload.';const retry=document.createElement('button');retry.className='primary';retry.style.maxWidth='220px';retry.textContent='Reload game';retry.onclick=()=>location.reload();$('loading').append(retry);console.error(error);}
try {renderer=new Renderer($('world'));world=makeWorld();addArena();renderer.setStatic(world.batch);world.batch.data.length=0;renderer.eye=[117,6.2,12.8];renderer.target=[107.7,1.4,0];$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();save();fail(new Error('The graphics context was interrupted. Your last saved progress is safe. Reload to continue.'));});addEventListener('resize',()=>renderer.resize());updateStarter();syncSound();setMode('intro');$('loading').hidden=true;document.body.dataset.version=VERSION;requestAnimationFrame(tick);}catch(error){fail(error);}
// A local-only harness supports deterministic UI tests; it is unavailable on the deployed site.
if(['localhost','127.0.0.1'].includes(location.hostname)){window.__WILDS_TEST__={pauseRendering:v=>{renderPaused=v;},snapshot:()=>({state:structuredClone(state),mode,battle:currentBattle?{...currentBattle,token:undefined}:null,fps,vertices:batch.data.length/9,storageAvailable}),teleport:(x,z)=>{if(state){state.position={x,z};allyPosition.x=x-1;allyPosition.z=z+1;}},encounter:(family=1,level=3,stage=0)=>beginBattle(member(family,level,stage)),guardian:i=>beginBattle({...member(GUARDIANS[i].family,GUARDIANS[i].level,Math.min(2,i+1)),guardian:i}),setRoll:v=>{roll=()=>v;},xp:n=>{gainXp(lead(),n);save();syncHud();},orbs:n=>{state.orbs=n;syncHud();},hurt:n=>{lead().hp=n;save();syncHud();},state:()=>state};}
if('serviceWorker' in navigator&&['https:','http:'].includes(location.protocol)){navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).catch(()=>{});}
