// Generated by npm run build. Cache scope: this game only.
self.GAME_OFFLINE={
  "prefix": "monterra-wilds-",
  "version": "1cf911a4c8ac",
  "assets": [
    "./",
    "./adventure.js",
    "./core.js",
    "./cover.svg",
    "./cover.webp",
    "./creatures.js",
    "./engine.js",
    "./game.js",
    "./game.json",
    "./geography.js",
    "./icon.svg",
    "./index.html",
    "./wilds.css",
    "./world.js",
    "../../studio/combat.js",
    "../../studio/core.js",
    "../../studio/models.js",
    "../../studio/passport.js",
    "../../studio/renderer.js",
    "../../studio/shaders.js",
    "../../studio/shell.js",
    "../../studio/studio.css",
    "../../studio/worker.js"
  ]
};
importScripts('../../studio/worker.js');
