import {Studio} from '../../studio/shell.js';
import {Batch,house,ring,burst,particles} from '../../studio/models.js';
import {clamp,seeded,starsFor} from '../../studio/core.js';
const names=['First flight','Skyline slalom','Drone commander','Harbor lights','Glass canyon','Cloud sentinel','The high road','Storm corridor','Thunder engine','Golden hour','Above the city','Sky guardian'];
export const config={slug:'iron-flight',name:'Iron Flight',title:'IRON<br><em>FLIGHT.</em>',genre:'AERIAL ACTION',accent:'#f1ca84',tagline:'Own the skyline. Thread the rings. Take the fight above the clouds.',subtitle:'THE SKY IS YOURS.',levels:names.map((name,i)=>({name,goal:i%3===2?'Fly the route, then disable the sky commander to clear the sector.':'Fly through navigation rings and clear the drone patrols. Stay above the city.'})),options:[{key:'suit',label:'SUIT MODULE',values:[['balanced','Mark I · balanced'],['agile','Mark II · agile'],['armored','Mark III · extra armor']]}],buttons:[{id:'primary',label:'FIRE',icon:'⌖'},{id:'special',label:'SHIELD',icon:'◇'},{id:'aux',label:'BOOST',icon:'ϟ'}],help:'Move the stick in any direction to steer through the skyline. Hold FIRE to lock onto a drone ahead. Fly through blue rings for points and repairs. Thread the exact center for a precision bonus; consecutive rings build a score chain. Below half armor, commanders fire spread volleys. SHIELD absorbs damage for three seconds. BOOST helps you escape a dangerous formation. Every third mission ends with a sky commander.',graphics:{fog:[.7,.69,.65],sun:[-.6,.6,-.3],lightColor:[1,.83,.65],exposure:1.2,fogNear:32,fogFar:100,shadowRadius:28}};
function suit(b,p,t,shield){b.frame(p,0);b.add('sphere',[0,0,0],[.33,.23,.63],'#973f35');b.add('box',[0,.08,-.3],[.25,.14,.28],'#b8523a');b.add('sphere',[0,.08,-.8],[.24,.24,.27],'#b18b4d');b.add('box',[0,.08,-1.04],[.17,.065,.025],'#9ee3e7');for(const s of [-1,1]){b.segment([s*.25,0,.4],[s*.25,-.06,1.12],.13,'#9f4235');b.add('box',[s*.25,-.05,1.2],[.13,.13,.22],'#bd9250');b.segment([s*.33,.04,-.2],[s*.63,0,.5],.12,'#a74b3c');b.add('sphere',[s*.63,0,.62],[.12,.12,.12],'#b58749');b.add('cone',[s*.25,-.05,1.65],[.10,.35+Math.sin(t*20)*.05,.10],'#baf5f2',[Math.PI/2,0,0]);}b.add('sphere',[0,-.15,-.25],[.1,.08,.1],'#c3ffff');if(shield)for(let i=0;i<12;i++){const a=i*Math.PI/6;b.add('gem',[Math.cos(a)*1.3,Math.sin(a)*1.3,0],[.065,.13,.065],'#b6eee5',[0,t,0]);}b.frame();}
export class Flight{
 constructor(s){this.s=s;}
 start(level,diff,options){this.level=level;this.diff=diff;this.module=options.suit||'balanced';this.player={x:0,y:4.5,hp:this.module==='armored'?125:100};this.maxHp=this.player.hp;this.distance=0;this.goal=600+level*70;this.speed=15+level*.5;this.cool=0;this.shield=0;this.shieldCd=0;this.boost=0;this.boostCd=0;this.rings=0;this.perfectRings=0;this.bestCombo=0;this.combo=0;this.score=0;this.chunk=-1;this.drones=[];this.gates=[];this.blocks=[];this.bullets=[];this.fx=[];this.random=seeded(412+level);this.bossSpawned=false;this.bossDefeated=false;this.prepare();this.rebuild();this.resize();this.hud();}
 prepare(){for(let d=35;d<this.goal-35;d+=24){const x=(Math.floor(this.random()*3)-1)*3,y=3+Math.floor(this.random()*3)*2;this.gates.push({x,y,d,done:false});if(d>60){const dx=(Math.floor(this.random()*3)-1)*3,dy=3+this.random()*4;this.drones.push({x:dx,y:dy,d:d+10,hp:50+this.level*4,max:50+this.level*4,cd:1.5,charge:0,done:false,boss:false});}if(this.level>0&&d%3!==0)this.blocks.push({x:-x||3,y:y>5?3:7,d:d+11,hit:false});}}
 rebuild(){const b=new Batch(),chunk=Math.floor(this.distance/55),start=chunk*55-20,end=start+170,rng=seeded(740+chunk);this.chunk=chunk;b.add('box',[0,-16,-(start+end)/2],[65,.5,(end-start)/2],'#587f83');b.add('box',[0,-13,-(start+end)/2],[9,.3,(end-start)/2],'#89928c');for(let d=Math.floor(start/9)*9;d<end;d+=9){for(const side of [-1,1]){const h=12+rng()*24,x=side*(12+rng()*9),z=-d;const col=['#9da7a4','#8c9b9a','#a6aaa0','#829594'][Math.floor(rng()*4)];b.add('box',[x,h/2-14,z],[2.8,h/2,2.8],col);b.add('box',[x,h-13.8,z],[3,.2,3],'#bcc1ae');for(let floor=-12;floor<h-15;floor+=2){b.add('box',[x-side*2.84,floor,z],[.025,.38,2.4],'#6d9398');b.add('box',[x,floor,z+2.84],[2.4,.38,.025],'#6d9398');}if(rng()>.6)b.add('cylinder',[x,h-12,z],[.05,1.8,.05],'#697c7d');}}this.s.setWorld(b);}
 resize(){this.s.renderer.fov=this.s.renderer.aspect<.85?1.0:.75;}
 action(id){if(id==='special'&&this.shieldCd<=0){this.shield=3.3;this.shieldCd=12;this.s.tone(600,.16);this.s.toast('Shield active');}if(id==='aux'&&this.boostCd<=0){this.boost=2.5;this.boostCd=9;this.s.tone(400,.18);}if(id==='primary')this.shoot();}
 shoot(){if(this.cool>0)return;const p=this.player,target=this.drones.filter(e=>!e.done&&e.hp>0&&e.d-this.distance>0&&e.d-this.distance<40).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y,a.d-this.distance)-Math.hypot(b.x-p.x,b.y-p.y,b.d-this.distance))[0];this.cool=.17;if(!target)return;this.bullets.push({x:p.x,y:p.y,z:-this.distance-1,target,life:1.3,enemy:false});this.s.tone(200,.055,'triangle');}
 hurt(amount){if(this.shield>0)return;this.player.hp-=amount*this.diff.damage;this.shield=.45;this.combo=0;this.s.tone(100,.15);burst(this.fx,this.player.x,this.player.y,-this.distance,'#efbe8b',12);}
 update(dt,input){const p=this.player,speed=this.module==='agile'?9:7;for(const key of ['cool','shield','shieldCd','boost','boostCd'])this[key]=Math.max(0,this[key]-dt);p.x=clamp(p.x+input.x*speed*dt,-5.3,5.3);p.y=clamp(p.y-input.z*speed*.75*dt,1.6,9);if(input.held('primary'))this.shoot();const boss=this.drones.find(e=>e.boss&&!e.done&&e.hp>0);this.distance+=this.speed*this.diff.speed*dt*(this.boost>0?1.65:1)*(boss&&this.distance>this.goal-25?0:1);if(Math.floor(this.distance/55)!==this.chunk)this.rebuild();
  if(this.level%3===2&&this.distance>this.goal-65&&!this.bossSpawned){this.bossSpawned=true;this.drones.push({x:0,y:5,d:this.distance+35,hp:450+this.level*30,max:450+this.level*30,cd:1,charge:0,done:false,boss:true});this.s.toast('Sky commander ahead. Dodge the warning beams and hold FIRE.',4000);}
  for(const e of this.drones){if(e.done||e.hp<=0)continue;const dz=e.d-this.distance;if(e.boss){if(e.hp<e.max*.5&&!e.phaseTwo){e.phaseTwo=true;this.s.toast('Commander overdrive · spread volleys incoming!',3200);}e.d=this.distance+24;e.x=Math.sin(this.s.time*.7)*3;e.y=5+Math.sin(this.s.time)*1.8;}if(dz>45)continue;if(dz< -3){e.done=true;continue;}if(dz<1.3&&Math.hypot(e.x-p.x,e.y-p.y)<1.2){this.hurt(18);e.done=true;}e.cd-=dt;if(e.charge>0){e.charge-=dt;if(e.charge<=0){const target={x:e.aim.x,y:e.aim.y,z:-this.distance+4},len=Math.hypot(target.x-e.x,target.y-e.y,target.z+e.d);for(const spread of e.phaseTwo?[-3.2,0,3.2]:[0])this.bullets.push({x:e.x,y:e.y,z:-e.d,vx:(target.x-e.x)/len*27+spread,vy:(target.y-e.y)/len*27,vz:(target.z+e.d)/len*27,life:3,enemy:true});e.cd=e.boss?(e.phaseTwo?.75:1.1):3;}}else if(e.cd<=0&&dz<32&&dz>8){e.charge=.8;e.aim={x:p.x,y:p.y};}}
  for(const g of this.gates)if(!g.done&&this.distance>=g.d){g.done=true;if(Math.hypot(g.x-p.x,g.y-p.y)<1.9){this.rings++;this.combo++;this.bestCombo=Math.max(this.bestCombo,this.combo);if(Math.hypot(g.x-p.x,g.y-p.y)<.65){this.perfectRings++;this.score+=180;this.s.toast(`Perfect center · +180 · chain ${this.combo}`);}this.score+=120+Math.min(10,this.combo)*20;p.hp=Math.min(this.maxHp,p.hp+3);burst(this.fx,p.x,p.y,-this.distance,'#b2f0e9',14);this.s.tone(640+this.combo*15,.09);}else this.combo=0;}
  for(const o of this.blocks)if(!o.hit&&Math.abs(o.d-this.distance)<1){if(Math.abs(o.x-p.x)<1.45&&Math.abs(o.y-p.y)<1.1)this.hurt(24);o.hit=true;}
  for(const v of this.bullets){v.life-=dt;if(v.enemy){const oldZ=v.z;v.x+=v.vx*dt;v.y+=v.vy*dt;v.z+=v.vz*dt;if(v.z>=-this.distance-1&&oldZ<=-this.distance+1&&Math.hypot(v.x-p.x,v.y-p.y)<.9){this.hurt(10);v.life=0;}}else{const e=v.target;if(e.done||e.hp<=0){v.life=0;continue;}const dx=e.x-v.x,dy=e.y-v.y,dz=-e.d-v.z,len=Math.hypot(dx,dy,dz),step=75*dt;if(len<step){e.hp-=25;v.life=0;burst(this.fx,e.x,e.y,-e.d,'#eac590',5);if(e.hp<=0){e.done=true;this.score+=e.boss?2000:180;if(e.boss)this.bossDefeated=true;burst(this.fx,e.x,e.y,-e.d,'#acebe5',24);}}else{v.x+=dx/len*step;v.y+=dy/len*step;v.z+=dz/len*step;}}}this.bullets=this.bullets.filter(v=>v.life>0);if(p.hp<=0){this.s.finish(false,{score:this.score,message:'Activate the shield when a warning beam appears, and use the full height of the flight corridor.'});return;}if(this.distance>=this.goal&&(this.level%3!==2||this.bossDefeated)){this.s.finish(true,{score:this.score+Math.round(p.hp*8),stars:starsFor(p.hp/this.maxHp*100,this.rings>=this.gates.length*.5),message:`Sector secured. ${this.rings}/${this.gates.length} navigation rings collected.`});return;}this.s.renderer.eye=[p.x*.3,p.y*.2+7,-this.distance+13];this.s.renderer.target=[p.x*.2,4.5,-this.distance-18];}
 draw(b,dt){const p=this.player;suit(b,[p.x,p.y,-this.distance],this.s.time,this.shield>0);for(const g of this.gates)if(!g.done&&g.d-this.distance<70)ring(b,[g.x,g.y,-g.d],1.65,'#a4e5df');for(const o of this.blocks)if(o.d-this.distance> -5&&o.d-this.distance<70){b.add('box',[o.x,o.y,-o.d],[1.3,.9,.5],'#657b7e');b.add('box',[o.x,o.y,-o.d+.52],[1.2,.04,.02],'#f0be81');}for(const e of this.drones)if(!e.done&&e.d-this.distance<70){const sz=e.boss?2.2:1;b.add('sphere',[e.x,e.y,-e.d],[sz*.53,sz*.28,sz*.45],e.boss?'#8f8872':'#8d9a96');for(const side of [-1,1]){b.add('box',[e.x+side*.68*sz,e.y,-e.d],[.42*sz,.06*sz,.27*sz],'#526e74');b.add('cylinder',[e.x+side*.87*sz,e.y+.05,-e.d],[.28*sz,.035,.28*sz],'#8ba9a6');}b.add('sphere',[e.x,e.y,-e.d+.4*sz],[.12*sz,.10*sz,.06],e.charge>0?'#ffd4a1':'#b6eced');if(e.charge>0)b.segment([e.x,e.y,-e.d],[e.aim.x,e.aim.y,-this.distance],.015,'#e7b698');}for(const v of this.bullets)b.add('sphere',[v.x,v.y,v.z],v.enemy?[.13,.13,.3]:[.07,.07,.3],v.enemy?'#f1bf91':'#d5ffff');particles(b,this.fx,dt);}
 hud(){const boss=this.drones.find(e=>e.boss&&!e.done);this.s.hud(boss?`Sky commander · ${Math.ceil(boss.hp/boss.max*100)}% armor`:`Fly the route · ${Math.max(0,Math.ceil(this.goal-this.distance))}m remaining`,this.distance/this.goal,[['ARMOR',Math.max(0,Math.ceil(this.player.hp))],['RINGS',this.rings],['SCORE',this.score]]);this.s.button('special',this.shield>0?'ACTIVE':'SHIELD',this.shieldCd);this.s.button('aux',this.boost>0?'BOOSTING':'BOOST',this.boostCd);}
 goals(){return [{label:'Perfect centers',value:this.perfectRings,target:3},{label:'Ring chain',value:this.bestCombo,target:5}];}
 bossInfo(){const e=this.drones.find(e=>e.boss&&!e.done);return e?{name:'Sky commander',hp:e.hp,max:e.max,phase:e.phaseTwo?2:1}:null;}
 snapshot(){return{distance:this.distance,hp:this.player.hp,x:this.player.x,y:this.player.y,rings:this.rings,perfectRings:this.perfectRings,shield:this.shield,score:this.score,boss:this.bossSpawned,bossDefeated:this.bossDefeated};}
}
if(typeof document!=='undefined')new Studio(config,Flight);
