import {Studio} from '../../studio/shell.js';
import {Batch,humanoid,ghost,tree,house,rock,burst,particles} from '../../studio/models.js';
import {clamp,distance,seeded,starsFor} from '../../studio/core.js';
import {healthBar,warningRing,advanceHazards} from '../../studio/combat.js';
const NINJAS=[{name:'Akari',color:'#a95649',power:'WHIRLWIND',damage:38,range:3.4,speed:6.5},{name:'Sora',color:'#577f9b',power:'FROST',damage:27,range:8,speed:6},{name:'Ren',color:'#608b72',power:'RESTORE',damage:31,range:3.9,speed:6.2}];
const names=['Lantern watch','Three guardians','The pale king','Bamboo whispers','Spirit crossing','The moon warden','Storm lanterns','The restless grove','Night sovereign','Mountain oath','The last lantern','Dawn of the village'];
export const config={slug:'ghost-village',name:'Ghost Village',title:'GHOST<br><em>VILLAGE.</em>',genre:'NINJA ADVENTURE',accent:'#a8d9c7',tagline:'Three guardians. One ancient village. Protect the light until dawn.',subtitle:'STAND TOGETHER.',levels:names.map((name,i)=>({name,goal:i%3===2?'Dispel the spirit guardian and protect the village shrine.':i<3?'Keep the shrine safe. Switch between the three ninja guardians.':'Fast shades and ranged wisps approach. Use your ninjas’ different powers.'})),options:[{key:'ninja',label:'LEAD GUARDIAN',values:[['0','Akari · whirlwind'],['1','Sora · frost shuriken'],['2','Ren · restore']]}],buttons:[{id:'primary',label:'STRIKE',icon:'✦'},{id:'special',label:'POWER',icon:'ϟ'},{id:'aux',label:'SWITCH',icon:'⇄'}],help:'Hold STRIKE to target nearby spirits. Akari uses a sweeping blade, Sora throws long-range shuriken, and Ren restores health. SWITCH changes the active ninja; the other two fight beside you. POWER has a separate cooldown for each ninja. Freeze with Sora, then strike with Akari to shatter. Hit the same spirit with all three leaders within four seconds to trigger a relay burst. Step outside a boss’s gold circles before they flash red. Defend the crystal shrine and collect spirit orbs to heal.',graphics:{fog:[.13,.25,.29],sun:[-.4,.9,-.3],lightColor:[.71,.9,1],exposure:1.1,fogNear:22,fogFar:65}};
export class Village{
 constructor(s){this.s=s;}
 start(level,diff,options){this.level=level;this.diff=diff;this.random=seeded(740+level);this.active=clamp(Number(options.ninja)||0,0,2);this.player={x:0,z:5,hp:100,yaw:Math.PI};this.shrine={x:0,z:0,hp:100};this.allies=[{x:-1.3,z:6,cd:0},{x:1.3,z:6,cd:0}];this.enemies=[];this.bolts=[];this.fx=[];this.orbs=[];this.cool=0;this.powers=[0,0,0];this.combo=0;this.relays=0;this.shatters=0;this.hazards=[];this.wave=0;this.waves=2+Math.floor(level/3);this.queue=0;this.spawnTime=1;this.breakTime=2;this.score=0;this.kills=0;this.attack=0;this.build();this.hud();}
 build(){const b=new Batch();b.add('box',[0,-.25,0],[25,.25,23],'#485f56');for(let x=-16;x<=16;x+=2)for(let z=-14;z<=14;z+=2)b.add('box',[x,.017,z],[.975,.018,.975],(x+z)%4?'#60716c':'#596c67');for(const side of [-1,1])for(let j=0;j<5;j++){const x=side*(19+j%2*3),z=-17+j*8;house(b,x,z,{pagoda:true,w:2.7,h:3+j%2,d:2,lit:true,color:'#837a61'});tree(b,x+side*3,z+3,1.1,'#3f655d');b.add('cylinder',[x-side*3.5,1.5,z],[.07,1.5,.07],'#746447');b.add('sphere',[x-side*3.5,3,z],[.28,.4,.28],'#efc795');}b.add('cylinder',[0,.18,0],[2,.2,2],'#80978a');b.add('cylinder',[0,.55,0],[1.1,.4,1.1],'#708d81');for(const x of [-4,4]){b.add('box',[x,2,-6],[.18,2,.18],'#945f49');}b.add('box',[0,4.1,-6],[4.6,.17,.3],'#935d47');b.add('box',[0,3.55,-6],[4.1,.13,.24],'#75644f');for(let i=0;i<18;i++)rock(b,-34+i*4,-26-this.random()*8,4+this.random()*6,'#456360');this.s.setWorld(b);this.s.renderer.eye=[0,25,23];this.s.renderer.target=[0,0,2];}
 action(id){const p=this.player,n=NINJAS[this.active];if(id==='aux'){this.active=(this.active+1)%3;this.s.toast(`${NINJAS[this.active].name} · ${NINJAS[this.active].power}`);this.s.tone(500);this.cool=0;}if(id==='special'&&this.powers[this.active]<=0){this.powers[this.active]=this.active===2?18:12;if(this.active===2){p.hp=Math.min(100,p.hp+38);this.shrine.hp=Math.min(100,this.shrine.hp+23);burst(this.fx,p.x,1,p.z,'#c4e9b9',32);this.s.toast('Ren restored your team and the shrine.');}else for(const e of this.enemies)if(distance(p,e)<(this.active===0?6.5:10)){e.hp-=this.active===0?100:45;e.frozen=this.active===1?4.5:1;burst(this.fx,e.x,1,e.z,this.active===0?'#f1c292':'#b8ecf0',14);}this.s.tone(260,.3);this.attack=.5;}if(id==='primary')this.strike();}
 strike(){if(this.cool>0)return;const p=this.player,n=NINJAS[this.active],targets=this.enemies.filter(e=>e.hp>0&&distance(p,e)<n.range).sort((a,b)=>distance(p,a)-distance(p,b));if(!targets.length)return;const e=targets[0];p.yaw=Math.atan2(e.x-p.x,e.z-p.z);this.cool=.38;this.attack=.22;this.combo=(this.combo+1)%3;const list=this.active===0?targets.slice(0,this.combo===0?4:2):[e];for(const v of list){if(this.active===0&&v.frozen>.35){v.hp-=35;v.frozen=0;this.shatters++;this.s.toast('Frost shatter! +35 damage');}
 v.relayMask=(v.relayTime>0?v.relayMask:0)|(1<<this.active);v.relayTime=4;
 if(v.relayMask===7){v.hp-=55;v.relayMask=0;this.relays++;this.s.toast('Three-guardian relay! +55 damage');burst(this.fx,v.x,1,v.z,'#fff0ab',22);}
 v.hp-=n.damage*(this.combo===0?1.45:1);v.flash=.13;if(this.active===1)v.frozen=.35;burst(this.fx,v.x,1,v.z,n.color,5);}if(this.active===1)this.bolts.push({x:p.x,z:p.z,tx:e.x,tz:e.z,life:.18,ally:true});this.s.tone(230+this.combo*70,.07);}
 update(dt,input){const p=this.player,n=NINJAS[this.active];this.cool=Math.max(0,this.cool-dt);this.attack=Math.max(0,this.attack-dt);this.powers=this.powers.map(v=>Math.max(0,v-dt));p.x=clamp(p.x+input.x*n.speed*dt,-16,16);p.z=clamp(p.z+input.z*n.speed*dt,-13,13);this.moving=Math.hypot(input.x,input.z)>.1;if(this.moving&&!this.attack)p.yaw=Math.atan2(input.x,input.z);if(input.held('primary'))this.strike();
  if(!this.queue&&!this.enemies.length){this.breakTime-=dt;if(this.breakTime<=0){if(this.wave>=this.waves){this.s.finish(true,{score:this.score+Math.round(this.shrine.hp*10),stars:starsFor(Math.min(p.hp,this.shrine.hp)),message:'The lanterns still burn. Your three guardians brought peace to the village.'});return;}this.wave++;this.queue=6+this.level+this.wave*2;this.spawnTime=0;this.breakTime=2.5;this.s.toast(`Spirit wave ${this.wave} / ${this.waves}`);}}
  if(this.queue>0){this.spawnTime-=dt;if(this.spawnTime<=0){const a=this.random()*Math.PI*2,boss=this.level%3===2&&this.queue===1&&this.wave===this.waves,type=boss?'boss':this.level>2&&this.queue%4===0?'wisp':this.queue%3===0?'shade':'ghost',hp=(boss?340+this.level*18:type==='shade'?58:90)+this.level*5;this.enemies.push({x:Math.cos(a)*16,z:Math.sin(a)*12,hp,max:hp,type,cd:1.2,frozen:0,flash:0,yaw:0,charge:0});this.queue--;this.spawnTime=1.05;}}
  this.allies.forEach((a,i)=>{const tx=p.x+(i?1.5:-1.5),tz=p.z+1.3;a.x+=(tx-a.x)*Math.min(1,dt*3);a.z+=(tz-a.z)*Math.min(1,dt*3);a.cd-=dt;const target=this.enemies.find(e=>distance(a,e)<3.5);if(target&&a.cd<=0){target.hp-=16;a.cd=.75;burst(this.fx,target.x,1,target.z,'#c7dbcf',3);}});
  for(const e of this.enemies){e.relayTime=Math.max(0,(e.relayTime||0)-dt);e.flash=Math.max(0,e.flash-dt);e.frozen=Math.max(0,e.frozen-dt);if(e.hp<=0||e.frozen>0)continue;
 if(e.type==='boss'){
  if(e.hp<e.max*.5&&!e.phaseTwo){e.phaseTwo=true;this.s.toast('Spirit guardian awakened · leave the gold circles!',3500);}
  e.pulse=(e.pulse??4)-dt;
  if(e.pulse<=0){e.pulse=e.phaseTwo?4.8:7;this.hazards.push({x:p.x,z:p.z,radius:e.phaseTwo?3.5:2.5,timer:1.3,damage:16});}
 }
 const target=distance(p,e)<4?p:this.shrine,d=distance(e,target);e.yaw=Math.atan2(target.x-e.x,target.z-e.z);e.cd-=dt;const speed=(e.type==='shade'?3.1:e.type==='boss'?1.1:1.5)*this.diff.speed,range=e.type==='wisp'?6:1.5;if(d>range){e.x+=Math.sin(e.yaw)*speed*dt;e.z+=Math.cos(e.yaw)*speed*dt;}if(e.charge>0){e.charge-=dt;if(e.charge<=0){if(e.type==='wisp'){const dx=e.aim.x-e.x,dz=e.aim.z-e.z,l=Math.hypot(dx,dz);this.bolts.push({x:e.x,z:e.z,vx:dx/l*7,vz:dz/l*7,life:3,ally:false});}else if(distance(e,target)<2.5){target.hp-=(e.type==='boss'?17:9)*this.diff.damage;this.s.tone(100,.12);burst(this.fx,target.x,1,target.z,'#f1c995',7);}e.cd=1.8;}}else if(d<=range+.2&&e.cd<=0){e.charge=.65;e.aim={x:target.x,z:target.z};}}
  this.hazards=advanceHazards(this.hazards,dt,p,damage=>{p.hp-=damage*this.diff.damage;burst(this.fx,p.x,1,p.z,'#edbc97',12);this.s.tone(85,.15);});this.bolts=this.bolts.filter(v=>{v.life-=dt;if(v.ally)return v.life>0;v.x+=v.vx*dt;v.z+=v.vz*dt;for(const target of [p,this.shrine])if(distance(v,target)<.7){target.hp-=8*this.diff.damage;v.life=0;}return v.life>0;});this.enemies=this.enemies.filter(e=>{if(e.hp>0)return true;this.score+=e.type==='boss'?1000:100;this.kills++;burst(this.fx,e.x,1,e.z,'#c2e3d0',16);if(this.kills%3===0)this.orbs.push({x:e.x,z:e.z});return false;});this.orbs=this.orbs.filter(v=>{if(distance(p,v)<1.3){p.hp=Math.min(100,p.hp+16);this.score+=25;this.s.tone(700);return false;}return true;});if(p.hp<=0||this.shrine.hp<=0){this.s.finish(false,{score:this.score,message:p.hp<=0?'Your team needs rest. Switch to Ren and use Restore when your health is low.':'The shrine needs your protection. Stay near the center and stop spirits before they arrive.'});return;}const t=[clamp(p.x*.4,-5,5),0,clamp(p.z*.4,-3,3)];this.s.renderer.target=t;this.s.renderer.eye=[t[0],this.s.renderer.aspect<.8?30:24,t[2]+22];}
 draw(b,dt){const p=this.player;humanoid(b,[p.x,0,p.z],p.yaw,{type:'ninja',color:NINJAS[this.active].color,trim:'#293b3d',time:this.s.time,walk:this.moving,attack:this.attack>0?1:0});this.allies.forEach((a,i)=>humanoid(b,[a.x,0,a.z],p.yaw,{type:'ninja',color:NINJAS[(this.active+i+1)%3].color,trim:'#293b3d',scale:.85,time:this.s.time+.2*i,walk:this.moving,attack:a.cd>.55?.8:0}));for(const h of this.hazards)warningRing(b,h,this.s.time);for(const e of this.enemies){healthBar(b,e);ghost(b,[e.x,.2,e.z],this.s.time,{color:e.frozen>0?'#8dc5d6':e.type==='boss'?'#b9b7d1':e.type==='shade'?'#86b6b8':'#b0d2c6',scale:e.type==='boss'?1.8:e.type==='shade'?.85:1,flash:e.flash>0,yaw:e.yaw});if(e.charge>0)b.add('cylinder',[e.x,.04,e.z],[1.8,.02,1.8],'#977d6c');}for(const v of this.orbs)b.add('gem',[v.x,.7+Math.sin(this.s.time*3)*.1,v.z],[.17,.25,.17],'#ddf0bd',[0,this.s.time,0]);for(const v of this.bolts)if(v.ally)b.segment([v.x,1,v.z],[v.tx,1,v.tz],.035,'#bfe8eb');else b.add('sphere',[v.x,1,v.z],[.14,.14,.14],'#d6b8dd');b.add('gem',[0,1.8+Math.sin(this.s.time)*.12,0],[.45,.95,.45],'#b5e2cb',[0,this.s.time*.4,0]);particles(b,this.fx,dt);}
 hud(){this.s.hud(`Protect the shrine · Wave ${Math.max(1,this.wave)} / ${this.waves}`,(this.wave-1+(this.enemies.length?0:.8))/this.waves,[['HEALTH',Math.max(0,Math.ceil(this.player.hp))],['SHRINE',Math.max(0,Math.ceil(this.shrine.hp))],['NINJA',NINJAS[this.active].name]]);this.s.button('special',NINJAS[this.active].power,this.powers[this.active]);}
 goals(){return [{label:'Frost shatters',value:this.shatters,target:2},{label:'Guardian relay',value:this.relays,target:1}];}
 bossInfo(){const e=this.enemies.find(e=>e.type==='boss'&&e.hp>0);return e?{name:'Spirit guardian',hp:e.hp,max:e.max,phase:e.phaseTwo?2:1}:null;}
 snapshot(){return {hp:this.player.hp,shrine:this.shrine.hp,ninja:this.active,powers:[...this.powers],wave:this.wave,enemies:this.enemies.length,score:this.score};}
}
if(typeof document!=='undefined')new Studio(config,Village);
