import { cp, mkdir, rm, readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { projectRoot, writeCatalog } from './catalog.mjs';

const games = await writeCatalog();
async function filesBelow(folder) {
  const result=[];
  for(const entry of await readdir(folder,{withFileTypes:true})) {
    const file=path.join(folder,entry.name);
    if(entry.isDirectory()) result.push(...await filesBelow(file));
    else result.push(file);
  }
  return result.sort();
}
const shared=(await filesBelow(path.join(projectRoot,'studio'))).map(file=>path.relative(projectRoot,file));
const oldPrefixes={'avengers-arena':'avengers-arena-','candy-pop':'tishaan-candy-pop-','iron-citadel':'iron-citadel-','monterra':'monterra-wilds-'};
for(const game of games) {
  const folder=path.join(projectRoot,'games',game.slug);
  const local=(await filesBelow(folder)).filter(file=>/\.(?:js|css|html|json|svg|png|webp|webmanifest)$/.test(file)&&path.basename(file)!=='sw.js');
  const hash=createHash('sha256');
  for(const file of [...local,...shared.map(f=>path.join(projectRoot,f))]) {hash.update(path.relative(projectRoot,file));hash.update(await readFile(file));}
  const config={prefix:oldPrefixes[game.slug]||`tishaan-${game.slug}-`,version:hash.digest('hex').slice(0,12),assets:['./',...local.map(file=>'./'+path.relative(folder,file)),...shared.map(file=>'../../'+file)]};
  await writeFile(path.join(folder,'sw.js'),`// Generated by npm run build. Cache scope: this game only.\nself.GAME_OFFLINE=${JSON.stringify(config,null,2)};\nimportScripts('../../studio/worker.js');\n`);
}
// Changing the hub or a catalog illustration automatically refreshes its offline cache.
const workerPath = path.join(projectRoot, 'sw.js');
const worker = await readFile(workerPath, 'utf8');
const fingerprint = createHash('sha256');
fingerprint.update(worker.replace(/^const CACHE = .*;$/m, ''));
const hubFiles = ['index.html', 'games/catalog.json', 'studio/passport.js', 'icon.svg', 'icon-192.png', 'icon-512.png', 'manifest.webmanifest', ...(await readdir(path.join(projectRoot, 'assets'))).sort().map(file => `assets/${file}`), ...games.flatMap(game => [game.icon, game.cover])];
for (const file of hubFiles) { fingerprint.update(file); fingerprint.update(await readFile(path.join(projectRoot, file))); }
const version = fingerprint.digest('hex').slice(0, 12);
await writeFile(workerPath, worker.replace(/^const CACHE = .*;$/m, `const CACHE = 'tishaan-game-zone-${version}';`));
const output = path.join(projectRoot, 'dist');
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
for (const file of ['index.html', 'assets', 'games', 'studio', 'sw.js', 'manifest.webmanifest', 'icon.svg', 'icon-192.png', 'icon-512.png', '.nojekyll']) {
  await cp(path.join(projectRoot, file), path.join(output, file), { recursive: true });
}
console.log(`Built Tishaan’s Game Zone and ${games.length} ${games.length === 1 ? 'game' : 'games'} in dist/.`);
