import {Studio} from '../../studio/shell.js';
import {Batch,tree,rock,burst,particles} from '../../studio/models.js';
import {clamp,distance,seeded,starsFor} from '../../studio/core.js';

const levels=['First Roar','Savanna Run','Hyena Ambush','Watering Hole','The Dry Gorge','Night Hunt','Rival Pride','Storm over the Plains','The Fallen King','Return to Pride Rock','Circle of Life','King of the Lands'];
export const config={slug:'pride-lands',name:'Pride Lands',title:'PRIDE<br><em>LANDS.</em>',genre:'LION ADVENTURE',accent:'#efb85b',tagline:'Grow from young hunter to guardian of the savanna. Hunt, survive and protect your pride.',subtitle:'RISE. ROAR. RULE.',levels:levels.map((name,i)=>({name,goal:i%3===2?'Defeat the rival alpha and survive the ambush.':i<4?'Track prey, feed and protect your pride.':'Cross a harsher territory with faster predators and stronger rivals.'})),options:[{key:'lion',label:'LION',values:[['0','Kito · balanced'],['1','Jabari · powerful'],['2','Amani · swift']]}],buttons:[{id:'primary',label:'POUNCE',icon:'✦'},{id:'special',label:'ROAR',icon:'◉'},{id:'aux',label:'SPRINT',icon:'➤'}],help:'Move with the stick or keyboard. Hold POUNCE near prey or enemies. ROAR briefly stuns nearby rivals and has a cooldown. SPRINT gives a burst of speed. Hunt gazelles to restore health, defeat hyenas and protect the pride marker until the mission is complete.',graphics:{fog:[.37,.24,.12],sun:[-.45,.86,-.25],lightColor:[1,.82,.55],exposure:1.18,fogNear:24,fogFar:82}};

function lion(b,p,yaw=0,o={}){const t=o.time||0,walk=o.walk?Math.sin(t*9)*.22:0,s=o.scale||1,body=o.body||'#b77734',mane=o.mane||'#4b2919';b.frame(p,yaw,s);b.add('sphere',[0,.72,0],[.72,.38,.3],body);b.add('sphere',[.62,.93,.03],[.38,.32,.31],o.adult===false?body:mane);b.add('sphere',[.68,.92,.16],[.28,.25,.26],body);b.add('sphere',[.84,.87,.34],[.19,.15,.18],body);for(const side of [-1,1]){b.add('cone',[.52+side*.16,1.2,.02],[.11,.14,.09],body,[0,0,side*.35]);const z1=side*walk;b.segment([-.35,.54,side*.18],[-.42,.08,side*.18+z1],.1,body);b.segment([.35,.54,side*.18],[.45,.08,side*.18-z1],.1,body);b.add('sphere',[.7,.99,side*.11],[.035,.035,.028],'#17120f');}b.segment([-.67,.78,0],[-1.12,.78+.12*Math.sin(t*4),.12],.08,body);b.add('sphere',[-1.18,.82,.14],[.12,.1,.1],mane);b.add('sphere',[.96,.83,.35],[.045,.04,.04],'#2e2119');b.frame();}
function hyena(b,p,yaw=0,o={}){b.frame(p,yaw,o.scale||1);const c=o.flash?'#ffe4a0':'#756451';b.add('sphere',[0,.55,0],[.56,.27,.25],c);b.add('sphere',[.5,.71,.05],[.28,.25,.24],c);b.add('sphere',[.68,.67,.26],[.2,.14,.17],c);for(const side of [-1,1]){b.add('cone',[.43+side*.1,.98,.02],[.09,.16,.07],'#4e4438');b.segment([-.35,.42,side*.17],[-.4,.06,side*.17],.085,c);b.segment([.35,.42,side*.17],[.42,.06,side*.17],.085,c);b.add('sphere',[.58,.76,side*.09],[.035,.03,.025],'#17120f');}b.segment([-.55,.58,0],[-.9,.48,.1],.055,c);b.frame();}
function gazelle(b,p,yaw=0,o={}){b.frame(p,yaw,o.scale||1);const c='#c99b61';b.add('sphere',[0,.68,0],[.5,.24,.2],c);b.add('sphere',[.48,.95,.05],[.2,.2,.18],c);b.add('sphere',[.65,.92,.24],[.13,.11,.12],c);for(const side of [-1,1]){b.segment([-.3,.52,side*.13],[-.34,.05,side*.13],.055,c);b.segment([.28,.52,side*.13],[.34,.05,side*.13],.055,c);b.segment([.5,1.1,side*.08],[.57,1.38,side*.08],.035,'#30261c');}b.frame();}

export class PrideLands{
 constructor(s){this.s=s;}
 start(level,diff,options){this.level=level;this.diff=diff;this.random=seeded(911+level*17);this.kind=clamp(Number(options.lion)||0,0,2);this.player={x:0,z:8,hp:100,yaw:Math.PI};this.enemies=[];this.prey=[];this.fx=[];this.score=0;this.kills=0;this.food=0;this.wave=0;this.waves=2+Math.floor(level/3);this.queue=0;this.spawn=0;this.break=2;this.attack=0;this.roar=0;this.sprint=0;this.mission=0;this.build();this.populatePrey();this.hud();}
 build(){const b=new Batch();b.add('box',[0,-.25,0],[34,.25,30],'#756038');for(let x=-30;x<=30;x+=3)for(let z=-26;z<=26;z+=3)b.add('box',[x,.012,z],[1.45,.012,1.45],((x+z)/3)%2?'#8c7540':'#7d6a39');for(let i=0;i<22;i++){const x=-28+this.random()*56,z=-24+this.random()*48;if(Math.hypot(x,z)<7)continue;if(i%3===0){tree(b,x,z,.65+this.random()*.5,'#687b3e');b.add('sphere',[x,3.4,z],[1.8,.55,1.4],'#71864c');}else rock(b,x,z,.7+this.random()*1.8,'#705b43');}b.add('low',[0,.9,-5],[3.8,1.2,3.1],'#786047',[.15,0,0]);b.add('low',[0,2,-7],[4.8,1.4,3.6],'#69533f',[.08,0,0]);b.add('cylinder',[0,.18,0],[1.7,.18,1.7],'#9b7e43');b.add('gem',[0,1.05,0],[.26,.8,.26],'#f2c568');this.s.setWorld(b);this.s.renderer.eye=[0,20,24];this.s.renderer.target=[0,0,2];}
 populatePrey(){for(let i=0;i<5;i++){const a=this.random()*Math.PI*2,r=8+this.random()*14;this.prey.push({x:Math.cos(a)*r,z:Math.sin(a)*r,hp:38,panic:0,yaw:a});}}
 action(id){if(id==='aux'&&this.sprint<=0){this.sprint=2.4;this.s.toast('Sprint!');this.s.tone(520,.08);}if(id==='special'&&this.roar<=0){this.roar=10;this.attack=.45;for(const e of this.enemies)if(distance(this.player,e)<7)e.stun=2.4;burst(this.fx,this.player.x,1,this.player.z,'#ffd071',26);this.s.toast('Your roar shakes the savanna.');this.s.tone(120,.42);}if(id==='primary')this.pounce();}
 pounce(){if(this.attack>0)return;const p=this.player;const targets=[...this.enemies.map(e=>({e,enemy:true})),...this.prey.map(e=>({e,enemy:false}))].filter(v=>v.e.hp>0&&distance(p,v.e)<2.4).sort((a,b)=>distance(p,a.e)-distance(p,b.e));if(!targets.length)return;const t=targets[0];p.yaw=Math.atan2(t.e.x-p.x,t.e.z-p.z);this.attack=.38;const power=this.kind===1?44:this.kind===2?30:36;t.e.hp-=power;burst(this.fx,t.e.x,.7,t.e.z,t.enemy?'#e9b35d':'#d8c28d',8);this.s.tone(t.enemy?170:220,.09);}
 spawnWave(){this.wave++;this.queue=4+this.level+this.wave*2;this.spawn=0;this.s.toast(`Rival pack ${this.wave} / ${this.waves}`);}
 update(dt,input){const p=this.player;this.attack=Math.max(0,this.attack-dt);this.roar=Math.max(0,this.roar-dt);this.sprint=Math.max(0,this.sprint-dt);const base=this.kind===2?7:this.kind===1?5.5:6.2;const speed=base*(this.sprint>0?1.55:1);p.x=clamp(p.x+input.x*speed*dt,-28,28);p.z=clamp(p.z+input.z*speed*dt,-24,24);this.moving=Math.hypot(input.x,input.z)>.1;if(this.moving&&!this.attack)p.yaw=Math.atan2(input.x,input.z);if(input.held('primary'))this.pounce();
  for(const g of this.prey){if(g.hp<=0)continue;const d=distance(p,g);if(d<6)g.panic=2;g.panic=Math.max(0,g.panic-dt);if(g.panic>0){const a=Math.atan2(g.x-p.x,g.z-p.z);g.yaw=a;g.x=clamp(g.x+Math.sin(a)*5.8*dt,-27,27);g.z=clamp(g.z+Math.cos(a)*5.8*dt,-23,23);}}
  this.prey=this.prey.filter(g=>{if(g.hp>0)return true;this.food++;this.score+=180;p.hp=Math.min(100,p.hp+20);burst(this.fx,g.x,.5,g.z,'#d7c58f',12);if(this.prey.length<4){const a=this.random()*Math.PI*2;this.prey.push({x:Math.cos(a)*18,z:Math.sin(a)*15,hp:38,panic:0,yaw:a});}return false;});
  if(!this.queue&&!this.enemies.length){this.break-=dt;if(this.break<=0){if(this.wave>=this.waves){this.mission+=dt;if(this.mission>2){this.s.finish(true,{score:this.score+Math.round(p.hp*12)+this.food*80,stars:starsFor(p.hp),message:'The pride is safe. Your roar carries across the savanna.'});return;}}else{this.spawnWave();this.break=2.5;}}}
  if(this.queue>0){this.spawn-=dt;if(this.spawn<=0){const a=this.random()*Math.PI*2,r=20+this.random()*5,boss=this.level%3===2&&this.queue===1&&this.wave===this.waves;this.enemies.push({x:Math.cos(a)*r,z:Math.sin(a)*r,hp:boss?260+this.level*12:66+this.level*5,max:boss?260+this.level*12:66+this.level*5,boss,cd:1,stun:0,flash:0,yaw:0});this.queue--;this.spawn=.9;}}
  for(const e of this.enemies){e.flash=Math.max(0,e.flash-dt);e.stun=Math.max(0,e.stun-dt);if(e.hp<=0||e.stun>0)continue;const d=distance(p,e);e.yaw=Math.atan2(p.x-e.x,p.z-e.z);e.cd-=dt;if(d>1.55){const v=(e.boss?2.3:3.1)*this.diff.speed;e.x+=Math.sin(e.yaw)*v*dt;e.z+=Math.cos(e.yaw)*v*dt;}else if(e.cd<=0){p.hp-=(e.boss?15:8)*this.diff.damage;e.cd=e.boss?1.1:1.45;e.flash=.15;burst(this.fx,p.x,.7,p.z,'#e2a25b',5);this.s.tone(90,.1);}}
  this.enemies=this.enemies.filter(e=>{if(e.hp>0)return true;this.kills++;this.score+=e.boss?900:130;burst(this.fx,e.x,.7,e.z,'#f1bd6a',14);return false;});if(p.hp<=0){this.s.finish(false,{score:this.score,message:'The savanna is unforgiving. Hunt gazelles to recover health and use ROAR before the pack surrounds you.'});return;}const t=[clamp(p.x*.45,-8,8),0,clamp(p.z*.45,-6,6)];this.s.renderer.target=t;this.s.renderer.eye=[t[0],this.s.renderer.aspect<.8?28:22,t[2]+22];}
 draw(b,dt){lion(b,[this.player.x,0,this.player.z],this.player.yaw,{time:this.s.time,walk:this.moving,scale:this.level<3?.9:1,adult:this.level>=2,body:this.kind===1?'#a85f2b':this.kind===2?'#c88b43':'#b97835',mane:this.kind===1?'#2d1b17':'#4a291b'});for(const g of this.prey)gazelle(b,[g.x,0,g.z],g.yaw,{scale:.9});for(const e of this.enemies){hyena(b,[e.x,0,e.z],e.yaw,{scale:e.boss?1.55:1,flash:e.flash>0});if(e.stun>0)b.add('gem',[e.x,1.8,e.z],[.09,.16,.09],'#f6d778',[0,this.s.time*2,0]);}particles(b,this.fx,dt);}
 hud(){this.s.hud(`Protect the pride · Pack ${Math.max(1,this.wave)} / ${this.waves}`,(this.wave-1+(this.enemies.length?0:.7))/this.waves,[['HEALTH',Math.max(0,Math.ceil(this.player.hp))],['HUNTS',this.food],['RIVALS',this.kills]]);this.s.button('special','ROAR',this.roar);this.s.button('aux','SPRINT',this.sprint);}
 snapshot(){return {hp:this.player.hp,wave:this.wave,kills:this.kills,hunts:this.food,enemies:this.enemies.length,score:this.score};}
}
if(typeof document!=='undefined')new Studio(config,PrideLands);
