// Generated by npm run build. Cache scope: this game only.
self.GAME_OFFLINE={
  "prefix": "avengers-arena-",
  "version": "94ff945089d3",
  "assets": [
    "./",
    "./cover.png",
    "./cover.webp",
    "./game.json",
    "./icon-192.png",
    "./icon-512.png",
    "./icon.svg",
    "./index.html",
    "./manifest.webmanifest",
    "./src/art.js",
    "./src/engine.js",
    "./src/game.js",
    "./src/scene.js",
    "./styles.css",
    "../../studio/core.js",
    "../../studio/models.js",
    "../../studio/renderer.js",
    "../../studio/shaders.js",
    "../../studio/shell.js",
    "../../studio/studio.css",
    "../../studio/worker.js"
  ]
};
importScripts('../../studio/worker.js');
